
(define (problem locality-01)
  (:domain locality)
  (:objects
   ;8 nodes conforming the network.
    node-A - node
    node-B - node
    node-C - node
    node-D - node
    node-E - node
    node-F - node
    node-G - node
    node-H - node
   ;50 data blocks to be scattered.
    block-0 - data-block
    block-1 - data-block
    block-2 - data-block
    block-3 - data-block
    block-4 - data-block
    block-5 - data-block
    block-6 - data-block
    block-7 - data-block
    block-8 - data-block
    block-9 - data-block
    block-10 - data-block
    block-11 - data-block
    block-12 - data-block
    block-13 - data-block
    block-14 - data-block
    block-15 - data-block
    block-16 - data-block
    block-17 - data-block
    block-18 - data-block
    block-19 - data-block
    block-20 - data-block
    block-21 - data-block
    block-22 - data-block
    block-23 - data-block
    block-24 - data-block
    block-25 - data-block
    block-26 - data-block
    block-27 - data-block
    block-28 - data-block
    block-29 - data-block
    block-30 - data-block
    block-31 - data-block
    block-32 - data-block
    block-33 - data-block
    block-34 - data-block
    block-35 - data-block
    block-36 - data-block
    block-37 - data-block
    block-38 - data-block
    block-39 - data-block
    block-40 - data-block
    block-41 - data-block
    block-42 - data-block
    block-43 - data-block
    block-44 - data-block
    block-45 - data-block
    block-46 - data-block
    block-47 - data-block
    block-48 - data-block
    block-49 - data-block
    count-0 - count
    count-1 - count
    count-2 - count
    count-3 - count
    count-4 - count
    count-5 - count
    count-6 - count
    count-7 - count
    count-8 - count
    count-9 - count
    count-10 - count
    count-11 - count
    count-12 - count
    count-13 - count
    count-14 - count
    count-15 - count
    count-16 - count
    count-17 - count
    count-18 - count
    count-19 - count
    count-20 - count
    count-21 - count
    count-22 - count
    count-23 - count
    count-24 - count
    count-25 - count
    count-26 - count
    count-27 - count
    count-28 - count
    count-29 - count
    count-30 - count
    count-31 - count
    count-32 - count
    count-33 - count
    count-34 - count
    count-35 - count
    count-36 - count
    count-37 - count
    count-38 - count
    count-39 - count
    count-40 - count
    count-41 - count
    count-42 - count
    count-43 - count
    count-44 - count
    count-45 - count
    count-46 - count
    count-47 - count
    count-48 - count
    count-49 - count
    count-50 - count
)
(:init
    (= (total-cost) 0)
    (= (last-request-point) 0)
    (sent node-A node-B count-0)
    (sent node-A node-C count-0)
    (sent node-A node-D count-0)
    (sent node-B node-A count-0)
    (sent node-B node-E count-0)
    (sent node-B node-F count-0)
    (sent node-C node-A count-0)
    (sent node-C node-G count-0)
    (sent node-D node-A count-0)
    (sent node-D node-H count-0)
    (sent node-E node-B count-0)
    (sent node-E node-F count-0)
    (sent node-E node-H count-0)
    (sent node-F node-B count-0)
    (sent node-F node-E count-0)
    (sent node-F node-H count-0)
    (sent node-G node-C count-0)
    (sent node-G node-H count-0)
    (sent node-H node-D count-0)
    (sent node-H node-E count-0)
    (sent node-H node-F count-0)
    (sent node-H node-G count-0)
    (connection node-A node-B)
    (connection node-A node-C)
    (connection node-A node-D)
    (connection node-B node-A)
    (connection node-B node-E)
    (connection node-B node-F)
    (connection node-C node-A)
    (connection node-C node-G)
    (connection node-D node-A)
    (connection node-D node-H)
    (connection node-E node-B)
    (connection node-E node-F)
    (connection node-E node-H)
    (connection node-F node-B)
    (connection node-F node-E)
    (connection node-F node-H)
    (connection node-G node-C)
    (connection node-G node-H)
    (connection node-H node-D)
    (connection node-H node-E)
    (connection node-H node-F)
    (connection node-H node-G)
    (next count-0 count-1)
    (next count-1 count-2)
    (next count-2 count-3)
    (next count-3 count-4)
    (next count-4 count-5)
    (next count-5 count-6)
    (next count-6 count-7)
    (next count-7 count-8)
    (next count-8 count-9)
    (next count-9 count-10)
    (next count-10 count-11)
    (next count-11 count-12)
    (next count-12 count-13)
    (next count-13 count-14)
    (next count-14 count-15)
    (next count-15 count-16)
    (next count-16 count-17)
    (next count-17 count-18)
    (next count-18 count-19)
    (next count-19 count-20)
    (next count-20 count-21)
    (next count-21 count-22)
    (next count-22 count-23)
    (next count-23 count-24)
    (next count-24 count-25)
    (next count-25 count-26)
    (next count-26 count-27)
    (next count-27 count-28)
    (next count-28 count-29)
    (next count-29 count-30)
    (next count-30 count-31)
    (next count-31 count-32)
    (next count-32 count-33)
    (next count-33 count-34)
    (next count-34 count-35)
    (next count-35 count-36)
    (next count-36 count-37)
    (next count-37 count-38)
    (next count-38 count-39)
    (next count-39 count-40)
    (next count-40 count-41)
    (next count-41 count-42)
    (next count-42 count-43)
    (next count-43 count-44)
    (next count-44 count-45)
    (next count-45 count-46)
    (next count-46 count-47)
    (next count-47 count-48)
    (next count-48 count-49)
    (next count-49 count-50)
    (= (request-point node-A node-B) 1)
    (= (request-point node-A node-C) 2)
    (= (request-point node-A node-D) 3)
    (= (request-point node-B node-A) 4)
    (= (request-point node-B node-E) 5)
    (= (request-point node-B node-F) 6)
    (= (request-point node-C node-A) 7)
    (= (request-point node-C node-G) 8)
    (= (request-point node-D node-A) 9)
    (= (request-point node-D node-H) 10)
    (= (request-point node-E node-B) 11)
    (= (request-point node-E node-F) 12)
    (= (request-point node-E node-H) 13)
    (= (request-point node-F node-B) 14)
    (= (request-point node-F node-E) 15)
    (= (request-point node-F node-H) 16)
    (= (request-point node-G node-C) 17)
    (= (request-point node-G node-H) 18)
    (= (request-point node-H node-D) 19)
    (= (request-point node-H node-E) 20)
    (= (request-point node-H node-F) 21)
    (= (request-point node-H node-G) 22)
    (= (segment-bandwidth node-A node-B) 12)
    (= (segment-bandwidth node-A node-C) 10)
    (= (segment-bandwidth node-A node-D) 10)
    (= (segment-bandwidth node-B node-A) 12)
    (= (segment-bandwidth node-B node-E) 10)
    (= (segment-bandwidth node-B node-F) 10)
    (= (segment-bandwidth node-C node-A) 10)
    (= (segment-bandwidth node-C node-G) 15)
    (= (segment-bandwidth node-D node-A) 10)
    (= (segment-bandwidth node-D node-H) 20)
    (= (segment-bandwidth node-E node-B) 10)
    (= (segment-bandwidth node-E node-F) 12)
    (= (segment-bandwidth node-E node-H) 10)
    (= (segment-bandwidth node-F node-B) 10)
    (= (segment-bandwidth node-F node-E) 12)
    (= (segment-bandwidth node-F node-H) 12)
    (= (segment-bandwidth node-G node-C) 15)
    (= (segment-bandwidth node-G node-H) 20)
    (= (segment-bandwidth node-H node-D) 20)
    (= (segment-bandwidth node-H node-E) 10)
    (= (segment-bandwidth node-H node-F) 12)
    (= (segment-bandwidth node-H node-G) 20)
    (= (block-relative-bandwidth count-1) 0.3)
    (= (block-relative-bandwidth count-2) 0.31)
    (= (block-relative-bandwidth count-3) 0.32)
    (= (block-relative-bandwidth count-4) 0.33)
    (= (block-relative-bandwidth count-5) 0.34)
    (= (block-relative-bandwidth count-6) 0.35)
    (= (block-relative-bandwidth count-7) 0.36)
    (= (block-relative-bandwidth count-8) 0.37)
    (= (block-relative-bandwidth count-9) 0.38)
    (= (block-relative-bandwidth count-10) 0.39)
    (= (block-relative-bandwidth count-11) 0.40)
    (= (block-relative-bandwidth count-12) 0.41)
    (= (block-relative-bandwidth count-13) 0.42)
    (= (block-relative-bandwidth count-14) 0.43)
    (= (block-relative-bandwidth count-15) 0.44)
    (= (block-relative-bandwidth count-16) 0.45)
    (= (block-relative-bandwidth count-17) 0.46)
    (= (block-relative-bandwidth count-18) 0.47)
    (= (block-relative-bandwidth count-19) 0.48)
    (= (block-relative-bandwidth count-20) 0.49)
    (= (block-relative-bandwidth count-21) 0.50)
    (= (block-relative-bandwidth count-22) 0.51)
    (= (block-relative-bandwidth count-23) 0.52)
    (= (block-relative-bandwidth count-24) 0.53)
    (= (block-relative-bandwidth count-25) 0.54)
    (= (block-relative-bandwidth count-26) 0.55)
    (= (block-relative-bandwidth count-27) 0.56)
    (= (block-relative-bandwidth count-28) 0.57)
    (= (block-relative-bandwidth count-29) 0.58)
    (= (block-relative-bandwidth count-30) 0.59)
    (= (block-relative-bandwidth count-31) 0.60)
    (= (block-relative-bandwidth count-32) 0.61)
    (= (block-relative-bandwidth count-33) 0.62)
    (= (block-relative-bandwidth count-34) 0.63)
    (= (block-relative-bandwidth count-35) 0.64)
    (= (block-relative-bandwidth count-36) 0.65)
    (= (block-relative-bandwidth count-37) 0.66)
    (= (block-relative-bandwidth count-38) 0.67)
    (= (block-relative-bandwidth count-39) 0.68)
    (= (block-relative-bandwidth count-40) 0.69)
    (= (block-relative-bandwidth count-41) 0.70)
    (= (block-relative-bandwidth count-42) 0.71)
    (= (block-relative-bandwidth count-43) 0.72)
    (= (block-relative-bandwidth count-44) 0.73)
    (= (block-relative-bandwidth count-45) 0.74)
    (= (block-relative-bandwidth count-46) 0.75)
    (= (block-relative-bandwidth count-47) 0.76)
    (= (block-relative-bandwidth count-48) 0.77)
    (= (block-relative-bandwidth count-49) 0.78)
    (= (block-relative-bandwidth count-50) 0.79)
    (= (kilobytes-sent count-1) 128)
    (= (kilobytes-sent count-2) 256)
    (= (kilobytes-sent count-3) 384)
    (= (kilobytes-sent count-4) 512)
    (= (kilobytes-sent count-5) 640)
    (= (kilobytes-sent count-6) 768)
    (= (kilobytes-sent count-7) 896)
    (= (kilobytes-sent count-8) 1024)
    (= (kilobytes-sent count-9) 1152)
    (= (kilobytes-sent count-10) 1280)
    (= (kilobytes-sent count-11) 1408)
    (= (kilobytes-sent count-12) 1536)
    (= (kilobytes-sent count-13) 1664)
    (= (kilobytes-sent count-14) 1792)
    (= (kilobytes-sent count-15) 1920)
    (= (kilobytes-sent count-16) 2048)
    (= (kilobytes-sent count-17) 2176)
    (= (kilobytes-sent count-18) 2304)
    (= (kilobytes-sent count-19) 2432)
    (= (kilobytes-sent count-20) 2560)
    (= (kilobytes-sent count-21) 2688)
    (= (kilobytes-sent count-22) 2816)
    (= (kilobytes-sent count-23) 2944)
    (= (kilobytes-sent count-24) 3072)
    (= (kilobytes-sent count-25) 3200)
    (= (kilobytes-sent count-26) 3328)
    (= (kilobytes-sent count-27) 3456)
    (= (kilobytes-sent count-28) 3584)
    (= (kilobytes-sent count-29) 3712)
    (= (kilobytes-sent count-30) 3840)
    (= (kilobytes-sent count-31) 3968)
    (= (kilobytes-sent count-32) 4096)
    (= (kilobytes-sent count-33) 4224)
    (= (kilobytes-sent count-34) 4352)
    (= (kilobytes-sent count-35) 4480)
    (= (kilobytes-sent count-36) 4608)
    (= (kilobytes-sent count-37) 4736)
    (= (kilobytes-sent count-38) 4864)
    (= (kilobytes-sent count-39) 4992)
    (= (kilobytes-sent count-40) 5120)
    (= (kilobytes-sent count-41) 5248)
    (= (kilobytes-sent count-42) 5376)
    (= (kilobytes-sent count-43) 5504)
    (= (kilobytes-sent count-44) 5632)
    (= (kilobytes-sent count-45) 5760)
    (= (kilobytes-sent count-46) 5888)
    (= (kilobytes-sent count-47) 6016)
    (= (kilobytes-sent count-48) 6144)
    (= (kilobytes-sent count-49) 6272)
    (= (kilobytes-sent count-50) 6400)
    (in block-0 node-A)
    (in block-1 node-A)
    (in block-2 node-A)
    (in block-3 node-A)
    (in block-4 node-A)
    (in block-5 node-A)
    (in block-6 node-A)
    (in block-7 node-A)
    (in block-8 node-B)
    (in block-9 node-B)
    (in block-10 node-B)
    (in block-11 node-B)
    (in block-12 node-B)
    (in block-13 node-B)
    (in block-14 node-B)
    (in block-15 node-B)
    (in block-16 node-C)
    (in block-17 node-C)
    (in block-18 node-C)
    (in block-19 node-C)
    (in block-20 node-C)
    (in block-21 node-C)
    (in block-22 node-C)
    (in block-23 node-C)
    (in block-24 node-C)
    (in block-25 node-D)
    (in block-26 node-D)
    (in block-27 node-D)
    (in block-28 node-D)
    (in block-29 node-D)
    (in block-30 node-D)
    (in block-31 node-D)
    (in block-32 node-D)
    (in block-33 node-D)
    (in block-34 node-E)
    (in block-35 node-E)
    (in block-36 node-E)
    (in block-37 node-E)
    (in block-38 node-E)
    (in block-39 node-F)
    (in block-40 node-F)
    (in block-41 node-F)
    (in block-42 node-F)
    (in block-43 node-F)
    (in block-44 node-G)
    (in block-45 node-G)
    (in block-46 node-G)
    (in block-47 node-H)
    (in block-48 node-H)
    (in block-49 node-H)
)
 (:goal (and
    (in block-0 node-A)
    (in block-1 node-A)
    (in block-2 node-A)
    (in block-3 node-A)
    (in block-4 node-A)
    (in block-5 node-A)
    (in block-6 node-A)
    (in block-7 node-A)
    (in block-8 node-A)
    (in block-9 node-A)
    (in block-10 node-A)
    (in block-11 node-A)
    (in block-12 node-A)
    (in block-13 node-A)
    (in block-14 node-A)
    (in block-15 node-A)
    (in block-16 node-A)
    (in block-17 node-A)
    (in block-18 node-A)
    (in block-19 node-A)
    (in block-20 node-A)
    (in block-21 node-A)
    (in block-22 node-A)
    (in block-23 node-A)
    (in block-24 node-A)
    (in block-25 node-A)
    (in block-26 node-A)
    (in block-27 node-A)
    (in block-28 node-A)
    (in block-29 node-A)
    (in block-30 node-A)
    (in block-31 node-A)
    (in block-32 node-A)
    (in block-33 node-A)
    (in block-34 node-A)
    (in block-35 node-A)
    (in block-36 node-A)
    (in block-37 node-A)
    (in block-38 node-A)
    (in block-39 node-A)
    (in block-40 node-A)
    (in block-41 node-A)
    (in block-42 node-A)
    (in block-43 node-A)
    (in block-44 node-A)
    (in block-45 node-A)
    (in block-46 node-A)
    (in block-47 node-A)
    (in block-48 node-A)
    (in block-49 node-A)
    (in block-0 node-B)
    (in block-1 node-B)
    (in block-2 node-B)
    (in block-3 node-B)
    (in block-4 node-B)
    (in block-5 node-B)
    (in block-6 node-B)
    (in block-7 node-B)
    (in block-8 node-B)
    (in block-9 node-B)
    (in block-10 node-B)
    (in block-11 node-B)
    (in block-12 node-B)
    (in block-13 node-B)
    (in block-14 node-B)
    (in block-15 node-B)
    (in block-16 node-B)
    (in block-17 node-B)
    (in block-18 node-B)
    (in block-19 node-B)
    (in block-20 node-B)
    (in block-21 node-B)
    (in block-22 node-B)
    (in block-23 node-B)
    (in block-24 node-B)
    (in block-25 node-B)
    (in block-26 node-B)
    (in block-27 node-B)
    (in block-28 node-B)
    (in block-29 node-B)
    (in block-30 node-B)
    (in block-31 node-B)
    (in block-32 node-B)
    (in block-33 node-B)
    (in block-34 node-B)
    (in block-35 node-B)
    (in block-36 node-B)
    (in block-37 node-B)
    (in block-38 node-B)
    (in block-39 node-B)
    (in block-40 node-B)
    (in block-41 node-B)
    (in block-42 node-B)
    (in block-43 node-B)
    (in block-44 node-B)
    (in block-45 node-B)
    (in block-46 node-B)
    (in block-47 node-B)
    (in block-48 node-B)
    (in block-49 node-B)
    (in block-0 node-C)
    (in block-1 node-C)
    (in block-2 node-C)
    (in block-3 node-C)
    (in block-4 node-C)
    (in block-5 node-C)
    (in block-6 node-C)
    (in block-7 node-C)
    (in block-8 node-C)
    (in block-9 node-C)
    (in block-10 node-C)
    (in block-11 node-C)
    (in block-12 node-C)
    (in block-13 node-C)
    (in block-14 node-C)
    (in block-15 node-C)
    (in block-16 node-C)
    (in block-17 node-C)
    (in block-18 node-C)
    (in block-19 node-C)
    (in block-20 node-C)
    (in block-21 node-C)
    (in block-22 node-C)
    (in block-23 node-C)
    (in block-24 node-C)
    (in block-25 node-C)
    (in block-26 node-C)
    (in block-27 node-C)
    (in block-28 node-C)
    (in block-29 node-C)
    (in block-30 node-C)
    (in block-31 node-C)
    (in block-32 node-C)
    (in block-33 node-C)
    (in block-34 node-C)
    (in block-35 node-C)
    (in block-36 node-C)
    (in block-37 node-C)
    (in block-38 node-C)
    (in block-39 node-C)
    (in block-40 node-C)
    (in block-41 node-C)
    (in block-42 node-C)
    (in block-43 node-C)
    (in block-44 node-C)
    (in block-45 node-C)
    (in block-46 node-C)
    (in block-47 node-C)
    (in block-48 node-C)
    (in block-49 node-C)
    (in block-0 node-D)
    (in block-1 node-D)
    (in block-2 node-D)
    (in block-3 node-D)
    (in block-4 node-D)
    (in block-5 node-D)
    (in block-6 node-D)
    (in block-7 node-D)
    (in block-8 node-D)
    (in block-9 node-D)
    (in block-10 node-D)
    (in block-11 node-D)
    (in block-12 node-D)
    (in block-13 node-D)
    (in block-14 node-D)
    (in block-15 node-D)
    (in block-16 node-D)
    (in block-17 node-D)
    (in block-18 node-D)
    (in block-19 node-D)
    (in block-20 node-D)
    (in block-21 node-D)
    (in block-22 node-D)
    (in block-23 node-D)
    (in block-24 node-D)
    (in block-25 node-D)
    (in block-26 node-D)
    (in block-27 node-D)
    (in block-28 node-D)
    (in block-29 node-D)
    (in block-30 node-D)
    (in block-31 node-D)
    (in block-32 node-D)
    (in block-33 node-D)
    (in block-34 node-D)
    (in block-35 node-D)
    (in block-36 node-D)
    (in block-37 node-D)
    (in block-38 node-D)
    (in block-39 node-D)
    (in block-40 node-D)
    (in block-41 node-D)
    (in block-42 node-D)
    (in block-43 node-D)
    (in block-44 node-D)
    (in block-45 node-D)
    (in block-46 node-D)
    (in block-47 node-D)
    (in block-48 node-D)
    (in block-49 node-D)
    (in block-0 node-E)
    (in block-1 node-E)
    (in block-2 node-E)
    (in block-3 node-E)
    (in block-4 node-E)
    (in block-5 node-E)
    (in block-6 node-E)
    (in block-7 node-E)
    (in block-8 node-E)
    (in block-9 node-E)
    (in block-10 node-E)
    (in block-11 node-E)
    (in block-12 node-E)
    (in block-13 node-E)
    (in block-14 node-E)
    (in block-15 node-E)
    (in block-16 node-E)
    (in block-17 node-E)
    (in block-18 node-E)
    (in block-19 node-E)
    (in block-20 node-E)
    (in block-21 node-E)
    (in block-22 node-E)
    (in block-23 node-E)
    (in block-24 node-E)
    (in block-25 node-E)
    (in block-26 node-E)
    (in block-27 node-E)
    (in block-28 node-E)
    (in block-29 node-E)
    (in block-30 node-E)
    (in block-31 node-E)
    (in block-32 node-E)
    (in block-33 node-E)
    (in block-34 node-E)
    (in block-35 node-E)
    (in block-36 node-E)
    (in block-37 node-E)
    (in block-38 node-E)
    (in block-39 node-E)
    (in block-40 node-E)
    (in block-41 node-E)
    (in block-42 node-E)
    (in block-43 node-E)
    (in block-44 node-E)
    (in block-45 node-E)
    (in block-46 node-E)
    (in block-47 node-E)
    (in block-48 node-E)
    (in block-49 node-E)
    (in block-0 node-F)
    (in block-1 node-F)
    (in block-2 node-F)
    (in block-3 node-F)
    (in block-4 node-F)
    (in block-5 node-F)
    (in block-6 node-F)
    (in block-7 node-F)
    (in block-8 node-F)
    (in block-9 node-F)
    (in block-10 node-F)
    (in block-11 node-F)
    (in block-12 node-F)
    (in block-13 node-F)
    (in block-14 node-F)
    (in block-15 node-F)
    (in block-16 node-F)
    (in block-17 node-F)
    (in block-18 node-F)
    (in block-19 node-F)
    (in block-20 node-F)
    (in block-21 node-F)
    (in block-22 node-F)
    (in block-23 node-F)
    (in block-24 node-F)
    (in block-25 node-F)
    (in block-26 node-F)
    (in block-27 node-F)
    (in block-28 node-F)
    (in block-29 node-F)
    (in block-30 node-F)
    (in block-31 node-F)
    (in block-32 node-F)
    (in block-33 node-F)
    (in block-34 node-F)
    (in block-35 node-F)
    (in block-36 node-F)
    (in block-37 node-F)
    (in block-38 node-F)
    (in block-39 node-F)
    (in block-40 node-F)
    (in block-41 node-F)
    (in block-42 node-F)
    (in block-43 node-F)
    (in block-44 node-F)
    (in block-45 node-F)
    (in block-46 node-F)
    (in block-47 node-F)
    (in block-48 node-F)
    (in block-49 node-F)
    (in block-0 node-G)
    (in block-1 node-G)
    (in block-2 node-G)
    (in block-3 node-G)
    (in block-4 node-G)
    (in block-5 node-G)
    (in block-6 node-G)
    (in block-7 node-G)
    (in block-8 node-G)
    (in block-9 node-G)
    (in block-10 node-G)
    (in block-11 node-G)
    (in block-12 node-G)
    (in block-13 node-G)
    (in block-14 node-G)
    (in block-15 node-G)
    (in block-16 node-G)
    (in block-17 node-G)
    (in block-18 node-G)
    (in block-19 node-G)
    (in block-20 node-G)
    (in block-21 node-G)
    (in block-22 node-G)
    (in block-23 node-G)
    (in block-24 node-G)
    (in block-25 node-G)
    (in block-26 node-G)
    (in block-27 node-G)
    (in block-28 node-G)
    (in block-29 node-G)
    (in block-30 node-G)
    (in block-31 node-G)
    (in block-32 node-G)
    (in block-33 node-G)
    (in block-34 node-G)
    (in block-35 node-G)
    (in block-36 node-G)
    (in block-37 node-G)
    (in block-38 node-G)
    (in block-39 node-G)
    (in block-40 node-G)
    (in block-41 node-G)
    (in block-42 node-G)
    (in block-43 node-G)
    (in block-44 node-G)
    (in block-45 node-G)
    (in block-46 node-G)
    (in block-47 node-G)
    (in block-48 node-G)
    (in block-49 node-G)
    (in block-0 node-H)
    (in block-1 node-H)
    (in block-2 node-H)
    (in block-3 node-H)
    (in block-4 node-H)
    (in block-5 node-H)
    (in block-6 node-H)
    (in block-7 node-H)
    (in block-8 node-H)
    (in block-9 node-H)
    (in block-10 node-H)
    (in block-11 node-H)
    (in block-12 node-H)
    (in block-13 node-H)
    (in block-14 node-H)
    (in block-15 node-H)
    (in block-16 node-H)
    (in block-17 node-H)
    (in block-18 node-H)
    (in block-19 node-H)
    (in block-20 node-H)
    (in block-21 node-H)
    (in block-22 node-H)
    (in block-23 node-H)
    (in block-24 node-H)
    (in block-25 node-H)
    (in block-26 node-H)
    (in block-27 node-H)
    (in block-28 node-H)
    (in block-29 node-H)
    (in block-30 node-H)
    (in block-31 node-H)
    (in block-32 node-H)
    (in block-33 node-H)
    (in block-34 node-H)
    (in block-35 node-H)
    (in block-36 node-H)
    (in block-37 node-H)
    (in block-38 node-H)
    (in block-39 node-H)
    (in block-40 node-H)
    (in block-41 node-H)
    (in block-42 node-H)
    (in block-43 node-H)
    (in block-44 node-H)
    (in block-45 node-H)
    (in block-46 node-H)
    (in block-47 node-H)
    (in block-48 node-H)
    (in block-49 node-H)
 ))
 (:metric minimize (total-cost))
)
