
(define (problem cube-01)
  (:domain locality)
  (:objects
   ;8 nodes conforming the network.
    node-A node-B node-C node-D node-E node-F node-G node-H - node
   ;20 data blocks to be scattered.
    block-0 block-1 block-2 block-3 block-4 block-5 block-6 block-7 block-8 block-9 - data-block
    block-10 block-11 block-12 block-13 block-14 block-15 block-16 block-17 block-18 block-19 - data-block
    count-0 - zero
    count-1 count-2 count-3 count-4 count-5 count-6 count-7 count-8 count-9 count-10 - non-zero
    count-11 count-12 count-13 count-14 count-15 count-16 count-17 count-18 count-19 count-20 - non-zero
)
(:init
    (= (total-cost) 0)
    (in block-0 node-A)
    (in block-1 node-B)
    (in block-2 node-C)
    (in block-3 node-D)
    (in block-4 node-E)
    (in block-5 node-F)
    (in block-6 node-G)
    (in block-7 node-H)
    (in block-8 node-A)
    (in block-9 node-B)
    (in block-10 node-C)
    (in block-11 node-D)
    (in block-12 node-E)
    (in block-13 node-F)
    (in block-14 node-G)
    (in block-15 node-H)
    (in block-16 node-A)
    (in block-17 node-B)
    (in block-18 node-C)
    (in block-19 node-D)
    (connection node-A node-E)
    (connection node-A node-B)
    (connection node-A node-C)
    (connection node-B node-A)
    (connection node-B node-G)
    (connection node-B node-D)
    (connection node-C node-A)
    (connection node-C node-D)
    (connection node-C node-F)
    (connection node-D node-C)
    (connection node-D node-B)
    (connection node-D node-H)
    (connection node-E node-A)
    (connection node-E node-G)
    (connection node-E node-F)
    (connection node-F node-E)
    (connection node-F node-C)
    (connection node-F node-H)
    (connection node-G node-E)
    (connection node-G node-B)
    (connection node-G node-H)
    (connection node-H node-G)
    (connection node-H node-F)
    (connection node-H node-D)
    (next count-0 count-1)
    (next count-1 count-2)
    (next count-2 count-3)
    (next count-3 count-4)
    (next count-4 count-5)
    (next count-5 count-6)
    (next count-6 count-7)
    (next count-7 count-8)
    (next count-8 count-9)
    (next count-9 count-10)
    (next count-10 count-11)
    (next count-11 count-12)
    (next count-12 count-13)
    (next count-13 count-14)
    (next count-14 count-15)
    (next count-15 count-16)
    (next count-16 count-17)
    (next count-17 count-18)
    (next count-18 count-19)
    (next count-19 count-20)
    (sent node-A node-E count-0)
    (sent node-A node-B count-0)
    (sent node-A node-C count-0)
    (sent node-B node-A count-0)
    (sent node-B node-G count-0)
    (sent node-B node-D count-0)
    (sent node-C node-A count-0)
    (sent node-C node-D count-0)
    (sent node-C node-F count-0)
    (sent node-D node-C count-0)
    (sent node-D node-B count-0)
    (sent node-D node-H count-0)
    (sent node-E node-A count-0)
    (sent node-E node-G count-0)
    (sent node-E node-F count-0)
    (sent node-F node-E count-0)
    (sent node-F node-C count-0)
    (sent node-F node-H count-0)
    (sent node-G node-E count-0)
    (sent node-G node-B count-0)
    (sent node-G node-H count-0)
    (sent node-H node-G count-0)
    (sent node-H node-F count-0)
    (sent node-H node-D count-0)
    (= (kilobytes-sent count-1) 128)
    (= (kilobytes-sent count-2) 256)
    (= (kilobytes-sent count-3) 384)
    (= (kilobytes-sent count-4) 512)
    (= (kilobytes-sent count-5) 640)
    (= (kilobytes-sent count-6) 768)
    (= (kilobytes-sent count-7) 896)
    (= (kilobytes-sent count-8) 1024)
    (= (kilobytes-sent count-9) 1152)
    (= (kilobytes-sent count-10) 1280)
    (= (kilobytes-sent count-11) 1408)
    (= (kilobytes-sent count-12) 1536)
    (= (kilobytes-sent count-13) 1664)
    (= (kilobytes-sent count-14) 1792)
    (= (kilobytes-sent count-15) 1920)
    (= (kilobytes-sent count-16) 2048)
    (= (kilobytes-sent count-17) 2176)
    (= (kilobytes-sent count-18) 2304)
    (= (kilobytes-sent count-19) 2432)
    (= (kilobytes-sent count-20) 2560)
    (= (segment-bandwidth node-A node-E) 1000)
    (= (segment-bandwidth node-A node-B) 5000)
    (= (segment-bandwidth node-A node-C) 1000)
    (= (segment-bandwidth node-B node-A) 5000)
    (= (segment-bandwidth node-B node-G) 5000)
    (= (segment-bandwidth node-B node-D) 1000)
    (= (segment-bandwidth node-C node-A) 1000)
    (= (segment-bandwidth node-C node-D) 1000)
    (= (segment-bandwidth node-C node-F) 1000)
    (= (segment-bandwidth node-D node-C) 1000)
    (= (segment-bandwidth node-D node-B) 1000)
    (= (segment-bandwidth node-D node-H) 1000)
    (= (segment-bandwidth node-E node-A) 1000)
    (= (segment-bandwidth node-E node-G) 1000)
    (= (segment-bandwidth node-E node-F) 1000)
    (= (segment-bandwidth node-F node-E) 1000)
    (= (segment-bandwidth node-F node-C) 1000)
    (= (segment-bandwidth node-F node-H) 1000)
    (= (segment-bandwidth node-G node-E) 1000)
    (= (segment-bandwidth node-G node-B) 5000)
    (= (segment-bandwidth node-G node-H) 1000)
    (= (segment-bandwidth node-H node-G) 1000)
    (= (segment-bandwidth node-H node-F) 1000)
    (= (segment-bandwidth node-H node-D) 1000)
    (= (block-relative-bandwidth count-1) 0.3)
    (= (block-relative-bandwidth count-2) 0.31)
    (= (block-relative-bandwidth count-3) 0.32)
    (= (block-relative-bandwidth count-4) 0.33)
    (= (block-relative-bandwidth count-5) 0.34)
    (= (block-relative-bandwidth count-6) 0.35)
    (= (block-relative-bandwidth count-7) 0.36)
    (= (block-relative-bandwidth count-8) 0.37)
    (= (block-relative-bandwidth count-9) 0.38)
    (= (block-relative-bandwidth count-10) 0.39)
    (= (block-relative-bandwidth count-11) 0.40)
    (= (block-relative-bandwidth count-12) 0.41)
    (= (block-relative-bandwidth count-13) 0.42)
    (= (block-relative-bandwidth count-14) 0.43)
    (= (block-relative-bandwidth count-15) 0.44)
    (= (block-relative-bandwidth count-16) 0.45)
    (= (block-relative-bandwidth count-17) 0.46)
    (= (block-relative-bandwidth count-18) 0.47)
    (= (block-relative-bandwidth count-19) 0.48)
    (= (block-relative-bandwidth count-20) 0.49)
)
 (:goal (and
    (in block-0 node-A)
    (in block-1 node-A)
    (in block-2 node-A)
    (in block-3 node-A)
    (in block-4 node-A)
    (in block-5 node-A)
    (in block-6 node-A)
    (in block-7 node-A)
    (in block-8 node-A)
    (in block-9 node-A)
    (in block-10 node-A)
    (in block-11 node-A)
    (in block-12 node-A)
    (in block-13 node-A)
    (in block-14 node-A)
    (in block-15 node-A)
    (in block-16 node-A)
    (in block-17 node-A)
    (in block-18 node-A)
    (in block-19 node-A)
    (in block-0 node-B)
    (in block-1 node-B)
    (in block-2 node-B)
    (in block-3 node-B)
    (in block-4 node-B)
    (in block-5 node-B)
    (in block-6 node-B)
    (in block-7 node-B)
    (in block-8 node-B)
    (in block-9 node-B)
    (in block-10 node-B)
    (in block-11 node-B)
    (in block-12 node-B)
    (in block-13 node-B)
    (in block-14 node-B)
    (in block-15 node-B)
    (in block-16 node-B)
    (in block-17 node-B)
    (in block-18 node-B)
    (in block-19 node-B)
    (in block-0 node-C)
    (in block-1 node-C)
    (in block-2 node-C)
    (in block-3 node-C)
    (in block-4 node-C)
    (in block-5 node-C)
    (in block-6 node-C)
    (in block-7 node-C)
    (in block-8 node-C)
    (in block-9 node-C)
    (in block-10 node-C)
    (in block-11 node-C)
    (in block-12 node-C)
    (in block-13 node-C)
    (in block-14 node-C)
    (in block-15 node-C)
    (in block-16 node-C)
    (in block-17 node-C)
    (in block-18 node-C)
    (in block-19 node-C)
    (in block-0 node-D)
    (in block-1 node-D)
    (in block-2 node-D)
    (in block-3 node-D)
    (in block-4 node-D)
    (in block-5 node-D)
    (in block-6 node-D)
    (in block-7 node-D)
    (in block-8 node-D)
    (in block-9 node-D)
    (in block-10 node-D)
    (in block-11 node-D)
    (in block-12 node-D)
    (in block-13 node-D)
    (in block-14 node-D)
    (in block-15 node-D)
    (in block-16 node-D)
    (in block-17 node-D)
    (in block-18 node-D)
    (in block-19 node-D)
    (in block-0 node-E)
    (in block-1 node-E)
    (in block-2 node-E)
    (in block-3 node-E)
    (in block-4 node-E)
    (in block-5 node-E)
    (in block-6 node-E)
    (in block-7 node-E)
    (in block-8 node-E)
    (in block-9 node-E)
    (in block-10 node-E)
    (in block-11 node-E)
    (in block-12 node-E)
    (in block-13 node-E)
    (in block-14 node-E)
    (in block-15 node-E)
    (in block-16 node-E)
    (in block-17 node-E)
    (in block-18 node-E)
    (in block-19 node-E)
    (in block-0 node-F)
    (in block-1 node-F)
    (in block-2 node-F)
    (in block-3 node-F)
    (in block-4 node-F)
    (in block-5 node-F)
    (in block-6 node-F)
    (in block-7 node-F)
    (in block-8 node-F)
    (in block-9 node-F)
    (in block-10 node-F)
    (in block-11 node-F)
    (in block-12 node-F)
    (in block-13 node-F)
    (in block-14 node-F)
    (in block-15 node-F)
    (in block-16 node-F)
    (in block-17 node-F)
    (in block-18 node-F)
    (in block-19 node-F)
    (in block-0 node-G)
    (in block-1 node-G)
    (in block-2 node-G)
    (in block-3 node-G)
    (in block-4 node-G)
    (in block-5 node-G)
    (in block-6 node-G)
    (in block-7 node-G)
    (in block-8 node-G)
    (in block-9 node-G)
    (in block-10 node-G)
    (in block-11 node-G)
    (in block-12 node-G)
    (in block-13 node-G)
    (in block-14 node-G)
    (in block-15 node-G)
    (in block-16 node-G)
    (in block-17 node-G)
    (in block-18 node-G)
    (in block-19 node-G)
    (in block-0 node-H)
    (in block-1 node-H)
    (in block-2 node-H)
    (in block-3 node-H)
    (in block-4 node-H)
    (in block-5 node-H)
    (in block-6 node-H)
    (in block-7 node-H)
    (in block-8 node-H)
    (in block-9 node-H)
    (in block-10 node-H)
    (in block-11 node-H)
    (in block-12 node-H)
    (in block-13 node-H)
    (in block-14 node-H)
    (in block-15 node-H)
    (in block-16 node-H)
    (in block-17 node-H)
    (in block-18 node-H)
    (in block-19 node-H)
 ))
 (:metric minimize (total-cost))
)
