
(define (problem tree-03)
  (:domain locality)
  (:objects
   ;31 nodes conforming the network.
    node-A node-B node-C node-D node-E node-F node-G node-H node-I node-J node-K node-L node-M node-N node-O node-P node-Q node-R node-S node-T node-U node-V node-W node-X node-Y node-Z node-AA node-AB node-AC node-AD node-AE - node
   ;40 data blocks to be scattered.
    block-0 block-1 block-2 block-3 block-4 block-5 block-6 block-7 block-8 block-9 - data-block
    block-10 block-11 block-12 block-13 block-14 block-15 block-16 block-17 block-18 block-19 - data-block
    block-20 block-21 block-22 block-23 block-24 block-25 block-26 block-27 block-28 block-29 - data-block
    block-30 block-31 block-32 block-33 block-34 block-35 block-36 block-37 block-38 block-39 - data-block
    count-0 - zero
    count-1 count-2 count-3 count-4 count-5 count-6 count-7 count-8 count-9 count-10 - non-zero
    count-11 count-12 count-13 count-14 count-15 count-16 count-17 count-18 count-19 count-20 - non-zero
    count-21 count-22 count-23 count-24 count-25 count-26 count-27 count-28 count-29 count-30 - non-zero
    count-31 count-32 count-33 count-34 count-35 count-36 count-37 count-38 count-39 count-40 - non-zero
)
(:init
    (= (total-cost) 0)
    (in block-0 node-A)
    (in block-1 node-B)
    (in block-2 node-C)
    (in block-3 node-D)
    (in block-4 node-E)
    (in block-5 node-F)
    (in block-6 node-G)
    (in block-7 node-H)
    (in block-8 node-I)
    (in block-9 node-J)
    (in block-10 node-K)
    (in block-11 node-L)
    (in block-12 node-M)
    (in block-13 node-N)
    (in block-14 node-O)
    (in block-15 node-P)
    (in block-16 node-Q)
    (in block-17 node-R)
    (in block-18 node-S)
    (in block-19 node-T)
    (in block-20 node-U)
    (in block-21 node-V)
    (in block-22 node-W)
    (in block-23 node-X)
    (in block-24 node-Y)
    (in block-25 node-Z)
    (in block-26 node-AA)
    (in block-27 node-AB)
    (in block-28 node-AC)
    (in block-29 node-AD)
    (in block-30 node-AE)
    (in block-31 node-A)
    (in block-32 node-B)
    (in block-33 node-C)
    (in block-34 node-D)
    (in block-35 node-E)
    (in block-36 node-F)
    (in block-37 node-G)
    (in block-38 node-H)
    (in block-39 node-I)
    (connection node-A node-B)
    (connection node-A node-C)
    (connection node-B node-A)
    (connection node-B node-D)
    (connection node-B node-E)
    (connection node-C node-A)
    (connection node-C node-F)
    (connection node-C node-G)
    (connection node-D node-B)
    (connection node-D node-H)
    (connection node-D node-I)
    (connection node-E node-B)
    (connection node-E node-J)
    (connection node-E node-K)
    (connection node-F node-C)
    (connection node-F node-L)
    (connection node-F node-M)
    (connection node-G node-C)
    (connection node-G node-N)
    (connection node-G node-O)
    (connection node-H node-D)
    (connection node-H node-P)
    (connection node-H node-Q)
    (connection node-I node-D)
    (connection node-I node-S)
    (connection node-I node-R)
    (connection node-J node-E)
    (connection node-J node-T)
    (connection node-J node-U)
    (connection node-K node-E)
    (connection node-K node-V)
    (connection node-K node-W)
    (connection node-L node-F)
    (connection node-L node-X)
    (connection node-L node-Y)
    (connection node-M node-F)
    (connection node-M node-Z)
    (connection node-M node-AA)
    (connection node-N node-G)
    (connection node-N node-AB)
    (connection node-N node-AC)
    (connection node-O node-G)
    (connection node-O node-AD)
    (connection node-O node-AE)
    (connection node-P node-H)
    (connection node-Q node-H)
    (connection node-R node-I)
    (connection node-S node-I)
    (connection node-T node-J)
    (connection node-U node-J)
    (connection node-V node-K)
    (connection node-W node-K)
    (connection node-X node-L)
    (connection node-Y node-L)
    (connection node-Z node-M)
    (connection node-AA node-M)
    (connection node-AB node-N)
    (connection node-AC node-N)
    (connection node-AD node-O)
    (connection node-AE node-O)
    (next count-0 count-1)
    (next count-1 count-2)
    (next count-2 count-3)
    (next count-3 count-4)
    (next count-4 count-5)
    (next count-5 count-6)
    (next count-6 count-7)
    (next count-7 count-8)
    (next count-8 count-9)
    (next count-9 count-10)
    (next count-10 count-11)
    (next count-11 count-12)
    (next count-12 count-13)
    (next count-13 count-14)
    (next count-14 count-15)
    (next count-15 count-16)
    (next count-16 count-17)
    (next count-17 count-18)
    (next count-18 count-19)
    (next count-19 count-20)
    (next count-20 count-21)
    (next count-21 count-22)
    (next count-22 count-23)
    (next count-23 count-24)
    (next count-24 count-25)
    (next count-25 count-26)
    (next count-26 count-27)
    (next count-27 count-28)
    (next count-28 count-29)
    (next count-29 count-30)
    (next count-30 count-31)
    (next count-31 count-32)
    (next count-32 count-33)
    (next count-33 count-34)
    (next count-34 count-35)
    (next count-35 count-36)
    (next count-36 count-37)
    (next count-37 count-38)
    (next count-38 count-39)
    (next count-39 count-40)
    (sent node-A node-B count-0)
    (sent node-A node-C count-0)
    (sent node-B node-A count-0)
    (sent node-B node-D count-0)
    (sent node-B node-E count-0)
    (sent node-C node-A count-0)
    (sent node-C node-F count-0)
    (sent node-C node-G count-0)
    (sent node-D node-B count-0)
    (sent node-D node-H count-0)
    (sent node-D node-I count-0)
    (sent node-E node-B count-0)
    (sent node-E node-J count-0)
    (sent node-E node-K count-0)
    (sent node-F node-C count-0)
    (sent node-F node-L count-0)
    (sent node-F node-M count-0)
    (sent node-G node-C count-0)
    (sent node-G node-N count-0)
    (sent node-G node-O count-0)
    (sent node-H node-D count-0)
    (sent node-H node-P count-0)
    (sent node-H node-Q count-0)
    (sent node-I node-D count-0)
    (sent node-I node-S count-0)
    (sent node-I node-R count-0)
    (sent node-J node-E count-0)
    (sent node-J node-T count-0)
    (sent node-J node-U count-0)
    (sent node-K node-E count-0)
    (sent node-K node-V count-0)
    (sent node-K node-W count-0)
    (sent node-L node-F count-0)
    (sent node-L node-X count-0)
    (sent node-L node-Y count-0)
    (sent node-M node-F count-0)
    (sent node-M node-Z count-0)
    (sent node-M node-AA count-0)
    (sent node-N node-G count-0)
    (sent node-N node-AB count-0)
    (sent node-N node-AC count-0)
    (sent node-O node-G count-0)
    (sent node-O node-AD count-0)
    (sent node-O node-AE count-0)
    (sent node-P node-H count-0)
    (sent node-Q node-H count-0)
    (sent node-R node-I count-0)
    (sent node-S node-I count-0)
    (sent node-T node-J count-0)
    (sent node-U node-J count-0)
    (sent node-V node-K count-0)
    (sent node-W node-K count-0)
    (sent node-X node-L count-0)
    (sent node-Y node-L count-0)
    (sent node-Z node-M count-0)
    (sent node-AA node-M count-0)
    (sent node-AB node-N count-0)
    (sent node-AC node-N count-0)
    (sent node-AD node-O count-0)
    (sent node-AE node-O count-0)
    (= (kilobytes-sent count-1) 128)
    (= (kilobytes-sent count-2) 256)
    (= (kilobytes-sent count-3) 384)
    (= (kilobytes-sent count-4) 512)
    (= (kilobytes-sent count-5) 640)
    (= (kilobytes-sent count-6) 768)
    (= (kilobytes-sent count-7) 896)
    (= (kilobytes-sent count-8) 1024)
    (= (kilobytes-sent count-9) 1152)
    (= (kilobytes-sent count-10) 1280)
    (= (kilobytes-sent count-11) 1408)
    (= (kilobytes-sent count-12) 1536)
    (= (kilobytes-sent count-13) 1664)
    (= (kilobytes-sent count-14) 1792)
    (= (kilobytes-sent count-15) 1920)
    (= (kilobytes-sent count-16) 2048)
    (= (kilobytes-sent count-17) 2176)
    (= (kilobytes-sent count-18) 2304)
    (= (kilobytes-sent count-19) 2432)
    (= (kilobytes-sent count-20) 2560)
    (= (kilobytes-sent count-21) 2688)
    (= (kilobytes-sent count-22) 2816)
    (= (kilobytes-sent count-23) 2944)
    (= (kilobytes-sent count-24) 3072)
    (= (kilobytes-sent count-25) 3200)
    (= (kilobytes-sent count-26) 3328)
    (= (kilobytes-sent count-27) 3456)
    (= (kilobytes-sent count-28) 3584)
    (= (kilobytes-sent count-29) 3712)
    (= (kilobytes-sent count-30) 3840)
    (= (kilobytes-sent count-31) 3968)
    (= (kilobytes-sent count-32) 4096)
    (= (kilobytes-sent count-33) 4224)
    (= (kilobytes-sent count-34) 4352)
    (= (kilobytes-sent count-35) 4480)
    (= (kilobytes-sent count-36) 4608)
    (= (kilobytes-sent count-37) 4736)
    (= (kilobytes-sent count-38) 4864)
    (= (kilobytes-sent count-39) 4992)
    (= (kilobytes-sent count-40) 5120)
    (= (segment-bandwidth node-A node-B) 100)
    (= (segment-bandwidth node-A node-C) 100)
    (= (segment-bandwidth node-B node-A) 100)
    (= (segment-bandwidth node-B node-D) 75)
    (= (segment-bandwidth node-B node-E) 75)
    (= (segment-bandwidth node-C node-A) 100)
    (= (segment-bandwidth node-C node-F) 75)
    (= (segment-bandwidth node-C node-G) 75)
    (= (segment-bandwidth node-D node-B) 75)
    (= (segment-bandwidth node-D node-H) 50)
    (= (segment-bandwidth node-D node-I) 50)
    (= (segment-bandwidth node-E node-B) 75)
    (= (segment-bandwidth node-E node-J) 50)
    (= (segment-bandwidth node-E node-K) 50)
    (= (segment-bandwidth node-F node-C) 75)
    (= (segment-bandwidth node-F node-L) 50)
    (= (segment-bandwidth node-F node-M) 50)
    (= (segment-bandwidth node-G node-C) 75)
    (= (segment-bandwidth node-G node-N) 50)
    (= (segment-bandwidth node-G node-O) 50)
    (= (segment-bandwidth node-H node-D) 50)
    (= (segment-bandwidth node-H node-P) 25)
    (= (segment-bandwidth node-H node-Q) 25)
    (= (segment-bandwidth node-I node-D) 50)
    (= (segment-bandwidth node-I node-S) 25)
    (= (segment-bandwidth node-I node-R) 25)
    (= (segment-bandwidth node-J node-E) 50)
    (= (segment-bandwidth node-J node-T) 25)
    (= (segment-bandwidth node-J node-U) 25)
    (= (segment-bandwidth node-K node-E) 50)
    (= (segment-bandwidth node-K node-V) 25)
    (= (segment-bandwidth node-K node-W) 25)
    (= (segment-bandwidth node-L node-F) 50)
    (= (segment-bandwidth node-L node-X) 25)
    (= (segment-bandwidth node-L node-Y) 25)
    (= (segment-bandwidth node-M node-F) 50)
    (= (segment-bandwidth node-M node-Z) 25)
    (= (segment-bandwidth node-M node-AA) 25)
    (= (segment-bandwidth node-N node-G) 50)
    (= (segment-bandwidth node-N node-AB) 25)
    (= (segment-bandwidth node-N node-AC) 25)
    (= (segment-bandwidth node-O node-G) 50)
    (= (segment-bandwidth node-O node-AD) 25)
    (= (segment-bandwidth node-O node-AE) 25)
    (= (segment-bandwidth node-P node-H) 25)
    (= (segment-bandwidth node-Q node-H) 25)
    (= (segment-bandwidth node-R node-I) 25)
    (= (segment-bandwidth node-S node-I) 25)
    (= (segment-bandwidth node-T node-J) 25)
    (= (segment-bandwidth node-U node-J) 25)
    (= (segment-bandwidth node-V node-K) 25)
    (= (segment-bandwidth node-W node-K) 25)
    (= (segment-bandwidth node-X node-L) 25)
    (= (segment-bandwidth node-Y node-L) 25)
    (= (segment-bandwidth node-Z node-M) 25)
    (= (segment-bandwidth node-AA node-M) 25)
    (= (segment-bandwidth node-AB node-N) 25)
    (= (segment-bandwidth node-AC node-N) 25)
    (= (segment-bandwidth node-AD node-O) 25)
    (= (segment-bandwidth node-AE node-O) 25)
    (= (block-relative-bandwidth count-1) 0.3)
    (= (block-relative-bandwidth count-2) 0.31)
    (= (block-relative-bandwidth count-3) 0.32)
    (= (block-relative-bandwidth count-4) 0.33)
    (= (block-relative-bandwidth count-5) 0.34)
    (= (block-relative-bandwidth count-6) 0.35)
    (= (block-relative-bandwidth count-7) 0.36)
    (= (block-relative-bandwidth count-8) 0.37)
    (= (block-relative-bandwidth count-9) 0.38)
    (= (block-relative-bandwidth count-10) 0.39)
    (= (block-relative-bandwidth count-11) 0.40)
    (= (block-relative-bandwidth count-12) 0.41)
    (= (block-relative-bandwidth count-13) 0.42)
    (= (block-relative-bandwidth count-14) 0.43)
    (= (block-relative-bandwidth count-15) 0.44)
    (= (block-relative-bandwidth count-16) 0.45)
    (= (block-relative-bandwidth count-17) 0.46)
    (= (block-relative-bandwidth count-18) 0.47)
    (= (block-relative-bandwidth count-19) 0.48)
    (= (block-relative-bandwidth count-20) 0.49)
    (= (block-relative-bandwidth count-21) 0.50)
    (= (block-relative-bandwidth count-22) 0.51)
    (= (block-relative-bandwidth count-23) 0.52)
    (= (block-relative-bandwidth count-24) 0.53)
    (= (block-relative-bandwidth count-25) 0.54)
    (= (block-relative-bandwidth count-26) 0.55)
    (= (block-relative-bandwidth count-27) 0.56)
    (= (block-relative-bandwidth count-28) 0.57)
    (= (block-relative-bandwidth count-29) 0.58)
    (= (block-relative-bandwidth count-30) 0.59)
    (= (block-relative-bandwidth count-31) 0.60)
    (= (block-relative-bandwidth count-32) 0.61)
    (= (block-relative-bandwidth count-33) 0.62)
    (= (block-relative-bandwidth count-34) 0.63)
    (= (block-relative-bandwidth count-35) 0.64)
    (= (block-relative-bandwidth count-36) 0.65)
    (= (block-relative-bandwidth count-37) 0.66)
    (= (block-relative-bandwidth count-38) 0.67)
    (= (block-relative-bandwidth count-39) 0.68)
    (= (block-relative-bandwidth count-40) 0.69)
)
 (:goal (and
    (in block-0 node-A)
    (in block-1 node-A)
    (in block-2 node-A)
    (in block-3 node-A)
    (in block-4 node-A)
    (in block-5 node-A)
    (in block-6 node-A)
    (in block-7 node-A)
    (in block-8 node-A)
    (in block-9 node-A)
    (in block-10 node-A)
    (in block-11 node-A)
    (in block-12 node-A)
    (in block-13 node-A)
    (in block-14 node-A)
    (in block-15 node-A)
    (in block-16 node-A)
    (in block-17 node-A)
    (in block-18 node-A)
    (in block-19 node-A)
    (in block-20 node-A)
    (in block-21 node-A)
    (in block-22 node-A)
    (in block-23 node-A)
    (in block-24 node-A)
    (in block-25 node-A)
    (in block-26 node-A)
    (in block-27 node-A)
    (in block-28 node-A)
    (in block-29 node-A)
    (in block-30 node-A)
    (in block-31 node-A)
    (in block-32 node-A)
    (in block-33 node-A)
    (in block-34 node-A)
    (in block-35 node-A)
    (in block-36 node-A)
    (in block-37 node-A)
    (in block-38 node-A)
    (in block-39 node-A)
    (in block-0 node-B)
    (in block-1 node-B)
    (in block-2 node-B)
    (in block-3 node-B)
    (in block-4 node-B)
    (in block-5 node-B)
    (in block-6 node-B)
    (in block-7 node-B)
    (in block-8 node-B)
    (in block-9 node-B)
    (in block-10 node-B)
    (in block-11 node-B)
    (in block-12 node-B)
    (in block-13 node-B)
    (in block-14 node-B)
    (in block-15 node-B)
    (in block-16 node-B)
    (in block-17 node-B)
    (in block-18 node-B)
    (in block-19 node-B)
    (in block-20 node-B)
    (in block-21 node-B)
    (in block-22 node-B)
    (in block-23 node-B)
    (in block-24 node-B)
    (in block-25 node-B)
    (in block-26 node-B)
    (in block-27 node-B)
    (in block-28 node-B)
    (in block-29 node-B)
    (in block-30 node-B)
    (in block-31 node-B)
    (in block-32 node-B)
    (in block-33 node-B)
    (in block-34 node-B)
    (in block-35 node-B)
    (in block-36 node-B)
    (in block-37 node-B)
    (in block-38 node-B)
    (in block-39 node-B)
    (in block-0 node-C)
    (in block-1 node-C)
    (in block-2 node-C)
    (in block-3 node-C)
    (in block-4 node-C)
    (in block-5 node-C)
    (in block-6 node-C)
    (in block-7 node-C)
    (in block-8 node-C)
    (in block-9 node-C)
    (in block-10 node-C)
    (in block-11 node-C)
    (in block-12 node-C)
    (in block-13 node-C)
    (in block-14 node-C)
    (in block-15 node-C)
    (in block-16 node-C)
    (in block-17 node-C)
    (in block-18 node-C)
    (in block-19 node-C)
    (in block-20 node-C)
    (in block-21 node-C)
    (in block-22 node-C)
    (in block-23 node-C)
    (in block-24 node-C)
    (in block-25 node-C)
    (in block-26 node-C)
    (in block-27 node-C)
    (in block-28 node-C)
    (in block-29 node-C)
    (in block-30 node-C)
    (in block-31 node-C)
    (in block-32 node-C)
    (in block-33 node-C)
    (in block-34 node-C)
    (in block-35 node-C)
    (in block-36 node-C)
    (in block-37 node-C)
    (in block-38 node-C)
    (in block-39 node-C)
    (in block-0 node-D)
    (in block-1 node-D)
    (in block-2 node-D)
    (in block-3 node-D)
    (in block-4 node-D)
    (in block-5 node-D)
    (in block-6 node-D)
    (in block-7 node-D)
    (in block-8 node-D)
    (in block-9 node-D)
    (in block-10 node-D)
    (in block-11 node-D)
    (in block-12 node-D)
    (in block-13 node-D)
    (in block-14 node-D)
    (in block-15 node-D)
    (in block-16 node-D)
    (in block-17 node-D)
    (in block-18 node-D)
    (in block-19 node-D)
    (in block-20 node-D)
    (in block-21 node-D)
    (in block-22 node-D)
    (in block-23 node-D)
    (in block-24 node-D)
    (in block-25 node-D)
    (in block-26 node-D)
    (in block-27 node-D)
    (in block-28 node-D)
    (in block-29 node-D)
    (in block-30 node-D)
    (in block-31 node-D)
    (in block-32 node-D)
    (in block-33 node-D)
    (in block-34 node-D)
    (in block-35 node-D)
    (in block-36 node-D)
    (in block-37 node-D)
    (in block-38 node-D)
    (in block-39 node-D)
    (in block-0 node-E)
    (in block-1 node-E)
    (in block-2 node-E)
    (in block-3 node-E)
    (in block-4 node-E)
    (in block-5 node-E)
    (in block-6 node-E)
    (in block-7 node-E)
    (in block-8 node-E)
    (in block-9 node-E)
    (in block-10 node-E)
    (in block-11 node-E)
    (in block-12 node-E)
    (in block-13 node-E)
    (in block-14 node-E)
    (in block-15 node-E)
    (in block-16 node-E)
    (in block-17 node-E)
    (in block-18 node-E)
    (in block-19 node-E)
    (in block-20 node-E)
    (in block-21 node-E)
    (in block-22 node-E)
    (in block-23 node-E)
    (in block-24 node-E)
    (in block-25 node-E)
    (in block-26 node-E)
    (in block-27 node-E)
    (in block-28 node-E)
    (in block-29 node-E)
    (in block-30 node-E)
    (in block-31 node-E)
    (in block-32 node-E)
    (in block-33 node-E)
    (in block-34 node-E)
    (in block-35 node-E)
    (in block-36 node-E)
    (in block-37 node-E)
    (in block-38 node-E)
    (in block-39 node-E)
    (in block-0 node-F)
    (in block-1 node-F)
    (in block-2 node-F)
    (in block-3 node-F)
    (in block-4 node-F)
    (in block-5 node-F)
    (in block-6 node-F)
    (in block-7 node-F)
    (in block-8 node-F)
    (in block-9 node-F)
    (in block-10 node-F)
    (in block-11 node-F)
    (in block-12 node-F)
    (in block-13 node-F)
    (in block-14 node-F)
    (in block-15 node-F)
    (in block-16 node-F)
    (in block-17 node-F)
    (in block-18 node-F)
    (in block-19 node-F)
    (in block-20 node-F)
    (in block-21 node-F)
    (in block-22 node-F)
    (in block-23 node-F)
    (in block-24 node-F)
    (in block-25 node-F)
    (in block-26 node-F)
    (in block-27 node-F)
    (in block-28 node-F)
    (in block-29 node-F)
    (in block-30 node-F)
    (in block-31 node-F)
    (in block-32 node-F)
    (in block-33 node-F)
    (in block-34 node-F)
    (in block-35 node-F)
    (in block-36 node-F)
    (in block-37 node-F)
    (in block-38 node-F)
    (in block-39 node-F)
    (in block-0 node-G)
    (in block-1 node-G)
    (in block-2 node-G)
    (in block-3 node-G)
    (in block-4 node-G)
    (in block-5 node-G)
    (in block-6 node-G)
    (in block-7 node-G)
    (in block-8 node-G)
    (in block-9 node-G)
    (in block-10 node-G)
    (in block-11 node-G)
    (in block-12 node-G)
    (in block-13 node-G)
    (in block-14 node-G)
    (in block-15 node-G)
    (in block-16 node-G)
    (in block-17 node-G)
    (in block-18 node-G)
    (in block-19 node-G)
    (in block-20 node-G)
    (in block-21 node-G)
    (in block-22 node-G)
    (in block-23 node-G)
    (in block-24 node-G)
    (in block-25 node-G)
    (in block-26 node-G)
    (in block-27 node-G)
    (in block-28 node-G)
    (in block-29 node-G)
    (in block-30 node-G)
    (in block-31 node-G)
    (in block-32 node-G)
    (in block-33 node-G)
    (in block-34 node-G)
    (in block-35 node-G)
    (in block-36 node-G)
    (in block-37 node-G)
    (in block-38 node-G)
    (in block-39 node-G)
    (in block-0 node-H)
    (in block-1 node-H)
    (in block-2 node-H)
    (in block-3 node-H)
    (in block-4 node-H)
    (in block-5 node-H)
    (in block-6 node-H)
    (in block-7 node-H)
    (in block-8 node-H)
    (in block-9 node-H)
    (in block-10 node-H)
    (in block-11 node-H)
    (in block-12 node-H)
    (in block-13 node-H)
    (in block-14 node-H)
    (in block-15 node-H)
    (in block-16 node-H)
    (in block-17 node-H)
    (in block-18 node-H)
    (in block-19 node-H)
    (in block-20 node-H)
    (in block-21 node-H)
    (in block-22 node-H)
    (in block-23 node-H)
    (in block-24 node-H)
    (in block-25 node-H)
    (in block-26 node-H)
    (in block-27 node-H)
    (in block-28 node-H)
    (in block-29 node-H)
    (in block-30 node-H)
    (in block-31 node-H)
    (in block-32 node-H)
    (in block-33 node-H)
    (in block-34 node-H)
    (in block-35 node-H)
    (in block-36 node-H)
    (in block-37 node-H)
    (in block-38 node-H)
    (in block-39 node-H)
    (in block-0 node-I)
    (in block-1 node-I)
    (in block-2 node-I)
    (in block-3 node-I)
    (in block-4 node-I)
    (in block-5 node-I)
    (in block-6 node-I)
    (in block-7 node-I)
    (in block-8 node-I)
    (in block-9 node-I)
    (in block-10 node-I)
    (in block-11 node-I)
    (in block-12 node-I)
    (in block-13 node-I)
    (in block-14 node-I)
    (in block-15 node-I)
    (in block-16 node-I)
    (in block-17 node-I)
    (in block-18 node-I)
    (in block-19 node-I)
    (in block-20 node-I)
    (in block-21 node-I)
    (in block-22 node-I)
    (in block-23 node-I)
    (in block-24 node-I)
    (in block-25 node-I)
    (in block-26 node-I)
    (in block-27 node-I)
    (in block-28 node-I)
    (in block-29 node-I)
    (in block-30 node-I)
    (in block-31 node-I)
    (in block-32 node-I)
    (in block-33 node-I)
    (in block-34 node-I)
    (in block-35 node-I)
    (in block-36 node-I)
    (in block-37 node-I)
    (in block-38 node-I)
    (in block-39 node-I)
    (in block-0 node-J)
    (in block-1 node-J)
    (in block-2 node-J)
    (in block-3 node-J)
    (in block-4 node-J)
    (in block-5 node-J)
    (in block-6 node-J)
    (in block-7 node-J)
    (in block-8 node-J)
    (in block-9 node-J)
    (in block-10 node-J)
    (in block-11 node-J)
    (in block-12 node-J)
    (in block-13 node-J)
    (in block-14 node-J)
    (in block-15 node-J)
    (in block-16 node-J)
    (in block-17 node-J)
    (in block-18 node-J)
    (in block-19 node-J)
    (in block-20 node-J)
    (in block-21 node-J)
    (in block-22 node-J)
    (in block-23 node-J)
    (in block-24 node-J)
    (in block-25 node-J)
    (in block-26 node-J)
    (in block-27 node-J)
    (in block-28 node-J)
    (in block-29 node-J)
    (in block-30 node-J)
    (in block-31 node-J)
    (in block-32 node-J)
    (in block-33 node-J)
    (in block-34 node-J)
    (in block-35 node-J)
    (in block-36 node-J)
    (in block-37 node-J)
    (in block-38 node-J)
    (in block-39 node-J)
    (in block-0 node-K)
    (in block-1 node-K)
    (in block-2 node-K)
    (in block-3 node-K)
    (in block-4 node-K)
    (in block-5 node-K)
    (in block-6 node-K)
    (in block-7 node-K)
    (in block-8 node-K)
    (in block-9 node-K)
    (in block-10 node-K)
    (in block-11 node-K)
    (in block-12 node-K)
    (in block-13 node-K)
    (in block-14 node-K)
    (in block-15 node-K)
    (in block-16 node-K)
    (in block-17 node-K)
    (in block-18 node-K)
    (in block-19 node-K)
    (in block-20 node-K)
    (in block-21 node-K)
    (in block-22 node-K)
    (in block-23 node-K)
    (in block-24 node-K)
    (in block-25 node-K)
    (in block-26 node-K)
    (in block-27 node-K)
    (in block-28 node-K)
    (in block-29 node-K)
    (in block-30 node-K)
    (in block-31 node-K)
    (in block-32 node-K)
    (in block-33 node-K)
    (in block-34 node-K)
    (in block-35 node-K)
    (in block-36 node-K)
    (in block-37 node-K)
    (in block-38 node-K)
    (in block-39 node-K)
    (in block-0 node-L)
    (in block-1 node-L)
    (in block-2 node-L)
    (in block-3 node-L)
    (in block-4 node-L)
    (in block-5 node-L)
    (in block-6 node-L)
    (in block-7 node-L)
    (in block-8 node-L)
    (in block-9 node-L)
    (in block-10 node-L)
    (in block-11 node-L)
    (in block-12 node-L)
    (in block-13 node-L)
    (in block-14 node-L)
    (in block-15 node-L)
    (in block-16 node-L)
    (in block-17 node-L)
    (in block-18 node-L)
    (in block-19 node-L)
    (in block-20 node-L)
    (in block-21 node-L)
    (in block-22 node-L)
    (in block-23 node-L)
    (in block-24 node-L)
    (in block-25 node-L)
    (in block-26 node-L)
    (in block-27 node-L)
    (in block-28 node-L)
    (in block-29 node-L)
    (in block-30 node-L)
    (in block-31 node-L)
    (in block-32 node-L)
    (in block-33 node-L)
    (in block-34 node-L)
    (in block-35 node-L)
    (in block-36 node-L)
    (in block-37 node-L)
    (in block-38 node-L)
    (in block-39 node-L)
    (in block-0 node-M)
    (in block-1 node-M)
    (in block-2 node-M)
    (in block-3 node-M)
    (in block-4 node-M)
    (in block-5 node-M)
    (in block-6 node-M)
    (in block-7 node-M)
    (in block-8 node-M)
    (in block-9 node-M)
    (in block-10 node-M)
    (in block-11 node-M)
    (in block-12 node-M)
    (in block-13 node-M)
    (in block-14 node-M)
    (in block-15 node-M)
    (in block-16 node-M)
    (in block-17 node-M)
    (in block-18 node-M)
    (in block-19 node-M)
    (in block-20 node-M)
    (in block-21 node-M)
    (in block-22 node-M)
    (in block-23 node-M)
    (in block-24 node-M)
    (in block-25 node-M)
    (in block-26 node-M)
    (in block-27 node-M)
    (in block-28 node-M)
    (in block-29 node-M)
    (in block-30 node-M)
    (in block-31 node-M)
    (in block-32 node-M)
    (in block-33 node-M)
    (in block-34 node-M)
    (in block-35 node-M)
    (in block-36 node-M)
    (in block-37 node-M)
    (in block-38 node-M)
    (in block-39 node-M)
    (in block-0 node-N)
    (in block-1 node-N)
    (in block-2 node-N)
    (in block-3 node-N)
    (in block-4 node-N)
    (in block-5 node-N)
    (in block-6 node-N)
    (in block-7 node-N)
    (in block-8 node-N)
    (in block-9 node-N)
    (in block-10 node-N)
    (in block-11 node-N)
    (in block-12 node-N)
    (in block-13 node-N)
    (in block-14 node-N)
    (in block-15 node-N)
    (in block-16 node-N)
    (in block-17 node-N)
    (in block-18 node-N)
    (in block-19 node-N)
    (in block-20 node-N)
    (in block-21 node-N)
    (in block-22 node-N)
    (in block-23 node-N)
    (in block-24 node-N)
    (in block-25 node-N)
    (in block-26 node-N)
    (in block-27 node-N)
    (in block-28 node-N)
    (in block-29 node-N)
    (in block-30 node-N)
    (in block-31 node-N)
    (in block-32 node-N)
    (in block-33 node-N)
    (in block-34 node-N)
    (in block-35 node-N)
    (in block-36 node-N)
    (in block-37 node-N)
    (in block-38 node-N)
    (in block-39 node-N)
    (in block-0 node-O)
    (in block-1 node-O)
    (in block-2 node-O)
    (in block-3 node-O)
    (in block-4 node-O)
    (in block-5 node-O)
    (in block-6 node-O)
    (in block-7 node-O)
    (in block-8 node-O)
    (in block-9 node-O)
    (in block-10 node-O)
    (in block-11 node-O)
    (in block-12 node-O)
    (in block-13 node-O)
    (in block-14 node-O)
    (in block-15 node-O)
    (in block-16 node-O)
    (in block-17 node-O)
    (in block-18 node-O)
    (in block-19 node-O)
    (in block-20 node-O)
    (in block-21 node-O)
    (in block-22 node-O)
    (in block-23 node-O)
    (in block-24 node-O)
    (in block-25 node-O)
    (in block-26 node-O)
    (in block-27 node-O)
    (in block-28 node-O)
    (in block-29 node-O)
    (in block-30 node-O)
    (in block-31 node-O)
    (in block-32 node-O)
    (in block-33 node-O)
    (in block-34 node-O)
    (in block-35 node-O)
    (in block-36 node-O)
    (in block-37 node-O)
    (in block-38 node-O)
    (in block-39 node-O)
    (in block-0 node-P)
    (in block-1 node-P)
    (in block-2 node-P)
    (in block-3 node-P)
    (in block-4 node-P)
    (in block-5 node-P)
    (in block-6 node-P)
    (in block-7 node-P)
    (in block-8 node-P)
    (in block-9 node-P)
    (in block-10 node-P)
    (in block-11 node-P)
    (in block-12 node-P)
    (in block-13 node-P)
    (in block-14 node-P)
    (in block-15 node-P)
    (in block-16 node-P)
    (in block-17 node-P)
    (in block-18 node-P)
    (in block-19 node-P)
    (in block-20 node-P)
    (in block-21 node-P)
    (in block-22 node-P)
    (in block-23 node-P)
    (in block-24 node-P)
    (in block-25 node-P)
    (in block-26 node-P)
    (in block-27 node-P)
    (in block-28 node-P)
    (in block-29 node-P)
    (in block-30 node-P)
    (in block-31 node-P)
    (in block-32 node-P)
    (in block-33 node-P)
    (in block-34 node-P)
    (in block-35 node-P)
    (in block-36 node-P)
    (in block-37 node-P)
    (in block-38 node-P)
    (in block-39 node-P)
    (in block-0 node-Q)
    (in block-1 node-Q)
    (in block-2 node-Q)
    (in block-3 node-Q)
    (in block-4 node-Q)
    (in block-5 node-Q)
    (in block-6 node-Q)
    (in block-7 node-Q)
    (in block-8 node-Q)
    (in block-9 node-Q)
    (in block-10 node-Q)
    (in block-11 node-Q)
    (in block-12 node-Q)
    (in block-13 node-Q)
    (in block-14 node-Q)
    (in block-15 node-Q)
    (in block-16 node-Q)
    (in block-17 node-Q)
    (in block-18 node-Q)
    (in block-19 node-Q)
    (in block-20 node-Q)
    (in block-21 node-Q)
    (in block-22 node-Q)
    (in block-23 node-Q)
    (in block-24 node-Q)
    (in block-25 node-Q)
    (in block-26 node-Q)
    (in block-27 node-Q)
    (in block-28 node-Q)
    (in block-29 node-Q)
    (in block-30 node-Q)
    (in block-31 node-Q)
    (in block-32 node-Q)
    (in block-33 node-Q)
    (in block-34 node-Q)
    (in block-35 node-Q)
    (in block-36 node-Q)
    (in block-37 node-Q)
    (in block-38 node-Q)
    (in block-39 node-Q)
    (in block-0 node-R)
    (in block-1 node-R)
    (in block-2 node-R)
    (in block-3 node-R)
    (in block-4 node-R)
    (in block-5 node-R)
    (in block-6 node-R)
    (in block-7 node-R)
    (in block-8 node-R)
    (in block-9 node-R)
    (in block-10 node-R)
    (in block-11 node-R)
    (in block-12 node-R)
    (in block-13 node-R)
    (in block-14 node-R)
    (in block-15 node-R)
    (in block-16 node-R)
    (in block-17 node-R)
    (in block-18 node-R)
    (in block-19 node-R)
    (in block-20 node-R)
    (in block-21 node-R)
    (in block-22 node-R)
    (in block-23 node-R)
    (in block-24 node-R)
    (in block-25 node-R)
    (in block-26 node-R)
    (in block-27 node-R)
    (in block-28 node-R)
    (in block-29 node-R)
    (in block-30 node-R)
    (in block-31 node-R)
    (in block-32 node-R)
    (in block-33 node-R)
    (in block-34 node-R)
    (in block-35 node-R)
    (in block-36 node-R)
    (in block-37 node-R)
    (in block-38 node-R)
    (in block-39 node-R)
    (in block-0 node-S)
    (in block-1 node-S)
    (in block-2 node-S)
    (in block-3 node-S)
    (in block-4 node-S)
    (in block-5 node-S)
    (in block-6 node-S)
    (in block-7 node-S)
    (in block-8 node-S)
    (in block-9 node-S)
    (in block-10 node-S)
    (in block-11 node-S)
    (in block-12 node-S)
    (in block-13 node-S)
    (in block-14 node-S)
    (in block-15 node-S)
    (in block-16 node-S)
    (in block-17 node-S)
    (in block-18 node-S)
    (in block-19 node-S)
    (in block-20 node-S)
    (in block-21 node-S)
    (in block-22 node-S)
    (in block-23 node-S)
    (in block-24 node-S)
    (in block-25 node-S)
    (in block-26 node-S)
    (in block-27 node-S)
    (in block-28 node-S)
    (in block-29 node-S)
    (in block-30 node-S)
    (in block-31 node-S)
    (in block-32 node-S)
    (in block-33 node-S)
    (in block-34 node-S)
    (in block-35 node-S)
    (in block-36 node-S)
    (in block-37 node-S)
    (in block-38 node-S)
    (in block-39 node-S)
    (in block-0 node-T)
    (in block-1 node-T)
    (in block-2 node-T)
    (in block-3 node-T)
    (in block-4 node-T)
    (in block-5 node-T)
    (in block-6 node-T)
    (in block-7 node-T)
    (in block-8 node-T)
    (in block-9 node-T)
    (in block-10 node-T)
    (in block-11 node-T)
    (in block-12 node-T)
    (in block-13 node-T)
    (in block-14 node-T)
    (in block-15 node-T)
    (in block-16 node-T)
    (in block-17 node-T)
    (in block-18 node-T)
    (in block-19 node-T)
    (in block-20 node-T)
    (in block-21 node-T)
    (in block-22 node-T)
    (in block-23 node-T)
    (in block-24 node-T)
    (in block-25 node-T)
    (in block-26 node-T)
    (in block-27 node-T)
    (in block-28 node-T)
    (in block-29 node-T)
    (in block-30 node-T)
    (in block-31 node-T)
    (in block-32 node-T)
    (in block-33 node-T)
    (in block-34 node-T)
    (in block-35 node-T)
    (in block-36 node-T)
    (in block-37 node-T)
    (in block-38 node-T)
    (in block-39 node-T)
    (in block-0 node-U)
    (in block-1 node-U)
    (in block-2 node-U)
    (in block-3 node-U)
    (in block-4 node-U)
    (in block-5 node-U)
    (in block-6 node-U)
    (in block-7 node-U)
    (in block-8 node-U)
    (in block-9 node-U)
    (in block-10 node-U)
    (in block-11 node-U)
    (in block-12 node-U)
    (in block-13 node-U)
    (in block-14 node-U)
    (in block-15 node-U)
    (in block-16 node-U)
    (in block-17 node-U)
    (in block-18 node-U)
    (in block-19 node-U)
    (in block-20 node-U)
    (in block-21 node-U)
    (in block-22 node-U)
    (in block-23 node-U)
    (in block-24 node-U)
    (in block-25 node-U)
    (in block-26 node-U)
    (in block-27 node-U)
    (in block-28 node-U)
    (in block-29 node-U)
    (in block-30 node-U)
    (in block-31 node-U)
    (in block-32 node-U)
    (in block-33 node-U)
    (in block-34 node-U)
    (in block-35 node-U)
    (in block-36 node-U)
    (in block-37 node-U)
    (in block-38 node-U)
    (in block-39 node-U)
    (in block-0 node-V)
    (in block-1 node-V)
    (in block-2 node-V)
    (in block-3 node-V)
    (in block-4 node-V)
    (in block-5 node-V)
    (in block-6 node-V)
    (in block-7 node-V)
    (in block-8 node-V)
    (in block-9 node-V)
    (in block-10 node-V)
    (in block-11 node-V)
    (in block-12 node-V)
    (in block-13 node-V)
    (in block-14 node-V)
    (in block-15 node-V)
    (in block-16 node-V)
    (in block-17 node-V)
    (in block-18 node-V)
    (in block-19 node-V)
    (in block-20 node-V)
    (in block-21 node-V)
    (in block-22 node-V)
    (in block-23 node-V)
    (in block-24 node-V)
    (in block-25 node-V)
    (in block-26 node-V)
    (in block-27 node-V)
    (in block-28 node-V)
    (in block-29 node-V)
    (in block-30 node-V)
    (in block-31 node-V)
    (in block-32 node-V)
    (in block-33 node-V)
    (in block-34 node-V)
    (in block-35 node-V)
    (in block-36 node-V)
    (in block-37 node-V)
    (in block-38 node-V)
    (in block-39 node-V)
    (in block-0 node-W)
    (in block-1 node-W)
    (in block-2 node-W)
    (in block-3 node-W)
    (in block-4 node-W)
    (in block-5 node-W)
    (in block-6 node-W)
    (in block-7 node-W)
    (in block-8 node-W)
    (in block-9 node-W)
    (in block-10 node-W)
    (in block-11 node-W)
    (in block-12 node-W)
    (in block-13 node-W)
    (in block-14 node-W)
    (in block-15 node-W)
    (in block-16 node-W)
    (in block-17 node-W)
    (in block-18 node-W)
    (in block-19 node-W)
    (in block-20 node-W)
    (in block-21 node-W)
    (in block-22 node-W)
    (in block-23 node-W)
    (in block-24 node-W)
    (in block-25 node-W)
    (in block-26 node-W)
    (in block-27 node-W)
    (in block-28 node-W)
    (in block-29 node-W)
    (in block-30 node-W)
    (in block-31 node-W)
    (in block-32 node-W)
    (in block-33 node-W)
    (in block-34 node-W)
    (in block-35 node-W)
    (in block-36 node-W)
    (in block-37 node-W)
    (in block-38 node-W)
    (in block-39 node-W)
    (in block-0 node-X)
    (in block-1 node-X)
    (in block-2 node-X)
    (in block-3 node-X)
    (in block-4 node-X)
    (in block-5 node-X)
    (in block-6 node-X)
    (in block-7 node-X)
    (in block-8 node-X)
    (in block-9 node-X)
    (in block-10 node-X)
    (in block-11 node-X)
    (in block-12 node-X)
    (in block-13 node-X)
    (in block-14 node-X)
    (in block-15 node-X)
    (in block-16 node-X)
    (in block-17 node-X)
    (in block-18 node-X)
    (in block-19 node-X)
    (in block-20 node-X)
    (in block-21 node-X)
    (in block-22 node-X)
    (in block-23 node-X)
    (in block-24 node-X)
    (in block-25 node-X)
    (in block-26 node-X)
    (in block-27 node-X)
    (in block-28 node-X)
    (in block-29 node-X)
    (in block-30 node-X)
    (in block-31 node-X)
    (in block-32 node-X)
    (in block-33 node-X)
    (in block-34 node-X)
    (in block-35 node-X)
    (in block-36 node-X)
    (in block-37 node-X)
    (in block-38 node-X)
    (in block-39 node-X)
    (in block-0 node-Y)
    (in block-1 node-Y)
    (in block-2 node-Y)
    (in block-3 node-Y)
    (in block-4 node-Y)
    (in block-5 node-Y)
    (in block-6 node-Y)
    (in block-7 node-Y)
    (in block-8 node-Y)
    (in block-9 node-Y)
    (in block-10 node-Y)
    (in block-11 node-Y)
    (in block-12 node-Y)
    (in block-13 node-Y)
    (in block-14 node-Y)
    (in block-15 node-Y)
    (in block-16 node-Y)
    (in block-17 node-Y)
    (in block-18 node-Y)
    (in block-19 node-Y)
    (in block-20 node-Y)
    (in block-21 node-Y)
    (in block-22 node-Y)
    (in block-23 node-Y)
    (in block-24 node-Y)
    (in block-25 node-Y)
    (in block-26 node-Y)
    (in block-27 node-Y)
    (in block-28 node-Y)
    (in block-29 node-Y)
    (in block-30 node-Y)
    (in block-31 node-Y)
    (in block-32 node-Y)
    (in block-33 node-Y)
    (in block-34 node-Y)
    (in block-35 node-Y)
    (in block-36 node-Y)
    (in block-37 node-Y)
    (in block-38 node-Y)
    (in block-39 node-Y)
    (in block-0 node-Z)
    (in block-1 node-Z)
    (in block-2 node-Z)
    (in block-3 node-Z)
    (in block-4 node-Z)
    (in block-5 node-Z)
    (in block-6 node-Z)
    (in block-7 node-Z)
    (in block-8 node-Z)
    (in block-9 node-Z)
    (in block-10 node-Z)
    (in block-11 node-Z)
    (in block-12 node-Z)
    (in block-13 node-Z)
    (in block-14 node-Z)
    (in block-15 node-Z)
    (in block-16 node-Z)
    (in block-17 node-Z)
    (in block-18 node-Z)
    (in block-19 node-Z)
    (in block-20 node-Z)
    (in block-21 node-Z)
    (in block-22 node-Z)
    (in block-23 node-Z)
    (in block-24 node-Z)
    (in block-25 node-Z)
    (in block-26 node-Z)
    (in block-27 node-Z)
    (in block-28 node-Z)
    (in block-29 node-Z)
    (in block-30 node-Z)
    (in block-31 node-Z)
    (in block-32 node-Z)
    (in block-33 node-Z)
    (in block-34 node-Z)
    (in block-35 node-Z)
    (in block-36 node-Z)
    (in block-37 node-Z)
    (in block-38 node-Z)
    (in block-39 node-Z)
    (in block-0 node-AA)
    (in block-1 node-AA)
    (in block-2 node-AA)
    (in block-3 node-AA)
    (in block-4 node-AA)
    (in block-5 node-AA)
    (in block-6 node-AA)
    (in block-7 node-AA)
    (in block-8 node-AA)
    (in block-9 node-AA)
    (in block-10 node-AA)
    (in block-11 node-AA)
    (in block-12 node-AA)
    (in block-13 node-AA)
    (in block-14 node-AA)
    (in block-15 node-AA)
    (in block-16 node-AA)
    (in block-17 node-AA)
    (in block-18 node-AA)
    (in block-19 node-AA)
    (in block-20 node-AA)
    (in block-21 node-AA)
    (in block-22 node-AA)
    (in block-23 node-AA)
    (in block-24 node-AA)
    (in block-25 node-AA)
    (in block-26 node-AA)
    (in block-27 node-AA)
    (in block-28 node-AA)
    (in block-29 node-AA)
    (in block-30 node-AA)
    (in block-31 node-AA)
    (in block-32 node-AA)
    (in block-33 node-AA)
    (in block-34 node-AA)
    (in block-35 node-AA)
    (in block-36 node-AA)
    (in block-37 node-AA)
    (in block-38 node-AA)
    (in block-39 node-AA)
    (in block-0 node-AB)
    (in block-1 node-AB)
    (in block-2 node-AB)
    (in block-3 node-AB)
    (in block-4 node-AB)
    (in block-5 node-AB)
    (in block-6 node-AB)
    (in block-7 node-AB)
    (in block-8 node-AB)
    (in block-9 node-AB)
    (in block-10 node-AB)
    (in block-11 node-AB)
    (in block-12 node-AB)
    (in block-13 node-AB)
    (in block-14 node-AB)
    (in block-15 node-AB)
    (in block-16 node-AB)
    (in block-17 node-AB)
    (in block-18 node-AB)
    (in block-19 node-AB)
    (in block-20 node-AB)
    (in block-21 node-AB)
    (in block-22 node-AB)
    (in block-23 node-AB)
    (in block-24 node-AB)
    (in block-25 node-AB)
    (in block-26 node-AB)
    (in block-27 node-AB)
    (in block-28 node-AB)
    (in block-29 node-AB)
    (in block-30 node-AB)
    (in block-31 node-AB)
    (in block-32 node-AB)
    (in block-33 node-AB)
    (in block-34 node-AB)
    (in block-35 node-AB)
    (in block-36 node-AB)
    (in block-37 node-AB)
    (in block-38 node-AB)
    (in block-39 node-AB)
    (in block-0 node-AC)
    (in block-1 node-AC)
    (in block-2 node-AC)
    (in block-3 node-AC)
    (in block-4 node-AC)
    (in block-5 node-AC)
    (in block-6 node-AC)
    (in block-7 node-AC)
    (in block-8 node-AC)
    (in block-9 node-AC)
    (in block-10 node-AC)
    (in block-11 node-AC)
    (in block-12 node-AC)
    (in block-13 node-AC)
    (in block-14 node-AC)
    (in block-15 node-AC)
    (in block-16 node-AC)
    (in block-17 node-AC)
    (in block-18 node-AC)
    (in block-19 node-AC)
    (in block-20 node-AC)
    (in block-21 node-AC)
    (in block-22 node-AC)
    (in block-23 node-AC)
    (in block-24 node-AC)
    (in block-25 node-AC)
    (in block-26 node-AC)
    (in block-27 node-AC)
    (in block-28 node-AC)
    (in block-29 node-AC)
    (in block-30 node-AC)
    (in block-31 node-AC)
    (in block-32 node-AC)
    (in block-33 node-AC)
    (in block-34 node-AC)
    (in block-35 node-AC)
    (in block-36 node-AC)
    (in block-37 node-AC)
    (in block-38 node-AC)
    (in block-39 node-AC)
    (in block-0 node-AD)
    (in block-1 node-AD)
    (in block-2 node-AD)
    (in block-3 node-AD)
    (in block-4 node-AD)
    (in block-5 node-AD)
    (in block-6 node-AD)
    (in block-7 node-AD)
    (in block-8 node-AD)
    (in block-9 node-AD)
    (in block-10 node-AD)
    (in block-11 node-AD)
    (in block-12 node-AD)
    (in block-13 node-AD)
    (in block-14 node-AD)
    (in block-15 node-AD)
    (in block-16 node-AD)
    (in block-17 node-AD)
    (in block-18 node-AD)
    (in block-19 node-AD)
    (in block-20 node-AD)
    (in block-21 node-AD)
    (in block-22 node-AD)
    (in block-23 node-AD)
    (in block-24 node-AD)
    (in block-25 node-AD)
    (in block-26 node-AD)
    (in block-27 node-AD)
    (in block-28 node-AD)
    (in block-29 node-AD)
    (in block-30 node-AD)
    (in block-31 node-AD)
    (in block-32 node-AD)
    (in block-33 node-AD)
    (in block-34 node-AD)
    (in block-35 node-AD)
    (in block-36 node-AD)
    (in block-37 node-AD)
    (in block-38 node-AD)
    (in block-39 node-AD)
    (in block-0 node-AE)
    (in block-1 node-AE)
    (in block-2 node-AE)
    (in block-3 node-AE)
    (in block-4 node-AE)
    (in block-5 node-AE)
    (in block-6 node-AE)
    (in block-7 node-AE)
    (in block-8 node-AE)
    (in block-9 node-AE)
    (in block-10 node-AE)
    (in block-11 node-AE)
    (in block-12 node-AE)
    (in block-13 node-AE)
    (in block-14 node-AE)
    (in block-15 node-AE)
    (in block-16 node-AE)
    (in block-17 node-AE)
    (in block-18 node-AE)
    (in block-19 node-AE)
    (in block-20 node-AE)
    (in block-21 node-AE)
    (in block-22 node-AE)
    (in block-23 node-AE)
    (in block-24 node-AE)
    (in block-25 node-AE)
    (in block-26 node-AE)
    (in block-27 node-AE)
    (in block-28 node-AE)
    (in block-29 node-AE)
    (in block-30 node-AE)
    (in block-31 node-AE)
    (in block-32 node-AE)
    (in block-33 node-AE)
    (in block-34 node-AE)
    (in block-35 node-AE)
    (in block-36 node-AE)
    (in block-37 node-AE)
    (in block-38 node-AE)
    (in block-39 node-AE)
 ))
 (:metric minimize (total-cost))
)
