
(define (problem fully-connected-02)
  (:domain locality)
  (:objects
   ;5 nodes conforming the network.
    node-A node-B node-C node-D node-E - node
   ;30 data blocks to be scattered.
    block-0 block-1 block-2 block-3 block-4 block-5 block-6 block-7 block-8 block-9 - data-block
    block-10 block-11 block-12 block-13 block-14 block-15 block-16 block-17 block-18 block-19 - data-block
    block-20 block-21 block-22 block-23 block-24 block-25 block-26 block-27 block-28 block-29 - data-block
    count-0 - zero
    count-1 count-2 count-3 count-4 count-5 count-6 count-7 count-8 count-9 count-10 - non-zero
    count-11 count-12 count-13 count-14 count-15 count-16 count-17 count-18 count-19 count-20 - non-zero
    count-21 count-22 count-23 count-24 count-25 count-26 count-27 count-28 count-29 count-30 - non-zero
)
(:init
    (= (total-cost) 0)
    (in block-0 node-A)
    (in block-1 node-B)
    (in block-2 node-C)
    (in block-3 node-D)
    (in block-4 node-E)
    (in block-5 node-A)
    (in block-6 node-B)
    (in block-7 node-C)
    (in block-8 node-D)
    (in block-9 node-E)
    (in block-10 node-A)
    (in block-11 node-B)
    (in block-12 node-C)
    (in block-13 node-D)
    (in block-14 node-E)
    (in block-15 node-A)
    (in block-16 node-B)
    (in block-17 node-C)
    (in block-18 node-D)
    (in block-19 node-E)
    (in block-20 node-A)
    (in block-21 node-B)
    (in block-22 node-C)
    (in block-23 node-D)
    (in block-24 node-E)
    (in block-25 node-A)
    (in block-26 node-B)
    (in block-27 node-C)
    (in block-28 node-D)
    (in block-29 node-E)
    (connection node-A node-B)
    (connection node-A node-C)
    (connection node-A node-D)
    (connection node-A node-E)
    (connection node-B node-A)
    (connection node-B node-C)
    (connection node-B node-D)
    (connection node-B node-E)
    (connection node-C node-A)
    (connection node-C node-B)
    (connection node-C node-D)
    (connection node-C node-E)
    (connection node-D node-A)
    (connection node-D node-B)
    (connection node-D node-C)
    (connection node-D node-E)
    (connection node-E node-A)
    (connection node-E node-B)
    (connection node-E node-C)
    (connection node-E node-D)
    (next count-0 count-1)
    (next count-1 count-2)
    (next count-2 count-3)
    (next count-3 count-4)
    (next count-4 count-5)
    (next count-5 count-6)
    (next count-6 count-7)
    (next count-7 count-8)
    (next count-8 count-9)
    (next count-9 count-10)
    (next count-10 count-11)
    (next count-11 count-12)
    (next count-12 count-13)
    (next count-13 count-14)
    (next count-14 count-15)
    (next count-15 count-16)
    (next count-16 count-17)
    (next count-17 count-18)
    (next count-18 count-19)
    (next count-19 count-20)
    (next count-20 count-21)
    (next count-21 count-22)
    (next count-22 count-23)
    (next count-23 count-24)
    (next count-24 count-25)
    (next count-25 count-26)
    (next count-26 count-27)
    (next count-27 count-28)
    (next count-28 count-29)
    (next count-29 count-30)
    (sent node-A node-B count-0)
    (sent node-A node-C count-0)
    (sent node-A node-D count-0)
    (sent node-A node-E count-0)
    (sent node-B node-A count-0)
    (sent node-B node-C count-0)
    (sent node-B node-D count-0)
    (sent node-B node-E count-0)
    (sent node-C node-A count-0)
    (sent node-C node-B count-0)
    (sent node-C node-D count-0)
    (sent node-C node-E count-0)
    (sent node-D node-A count-0)
    (sent node-D node-B count-0)
    (sent node-D node-C count-0)
    (sent node-D node-E count-0)
    (sent node-E node-A count-0)
    (sent node-E node-B count-0)
    (sent node-E node-C count-0)
    (sent node-E node-D count-0)
    (= (kilobytes-sent count-1) 128)
    (= (kilobytes-sent count-2) 256)
    (= (kilobytes-sent count-3) 384)
    (= (kilobytes-sent count-4) 512)
    (= (kilobytes-sent count-5) 640)
    (= (kilobytes-sent count-6) 768)
    (= (kilobytes-sent count-7) 896)
    (= (kilobytes-sent count-8) 1024)
    (= (kilobytes-sent count-9) 1152)
    (= (kilobytes-sent count-10) 1280)
    (= (kilobytes-sent count-11) 1408)
    (= (kilobytes-sent count-12) 1536)
    (= (kilobytes-sent count-13) 1664)
    (= (kilobytes-sent count-14) 1792)
    (= (kilobytes-sent count-15) 1920)
    (= (kilobytes-sent count-16) 2048)
    (= (kilobytes-sent count-17) 2176)
    (= (kilobytes-sent count-18) 2304)
    (= (kilobytes-sent count-19) 2432)
    (= (kilobytes-sent count-20) 2560)
    (= (kilobytes-sent count-21) 2688)
    (= (kilobytes-sent count-22) 2816)
    (= (kilobytes-sent count-23) 2944)
    (= (kilobytes-sent count-24) 3072)
    (= (kilobytes-sent count-25) 3200)
    (= (kilobytes-sent count-26) 3328)
    (= (kilobytes-sent count-27) 3456)
    (= (kilobytes-sent count-28) 3584)
    (= (kilobytes-sent count-29) 3712)
    (= (kilobytes-sent count-30) 3840)
    (= (segment-bandwidth node-A node-B) 200)
    (= (segment-bandwidth node-A node-C) 100)
    (= (segment-bandwidth node-A node-D) 100)
    (= (segment-bandwidth node-A node-E) 200)
    (= (segment-bandwidth node-B node-A) 200)
    (= (segment-bandwidth node-B node-C) 200)
    (= (segment-bandwidth node-B node-D) 100)
    (= (segment-bandwidth node-B node-E) 100)
    (= (segment-bandwidth node-C node-A) 100)
    (= (segment-bandwidth node-C node-B) 200)
    (= (segment-bandwidth node-C node-D) 200)
    (= (segment-bandwidth node-C node-E) 100)
    (= (segment-bandwidth node-D node-A) 100)
    (= (segment-bandwidth node-D node-B) 100)
    (= (segment-bandwidth node-D node-C) 200)
    (= (segment-bandwidth node-D node-E) 200)
    (= (segment-bandwidth node-E node-A) 200)
    (= (segment-bandwidth node-E node-B) 100)
    (= (segment-bandwidth node-E node-C) 100)
    (= (segment-bandwidth node-E node-D) 200)
    (= (block-relative-bandwidth count-1) 0.3)
    (= (block-relative-bandwidth count-2) 0.3)
    (= (block-relative-bandwidth count-3) 0.3)
    (= (block-relative-bandwidth count-4) 0.3)
    (= (block-relative-bandwidth count-5) 0.3)
    (= (block-relative-bandwidth count-6) 0.3)
    (= (block-relative-bandwidth count-7) 0.3)
    (= (block-relative-bandwidth count-8) 0.3)
    (= (block-relative-bandwidth count-9) 0.3)
    (= (block-relative-bandwidth count-10) 0.3)
    (= (block-relative-bandwidth count-11) 0.3)
    (= (block-relative-bandwidth count-12) 0.3)
    (= (block-relative-bandwidth count-13) 0.3)
    (= (block-relative-bandwidth count-14) 0.3)
    (= (block-relative-bandwidth count-15) 0.3)
    (= (block-relative-bandwidth count-16) 0.3)
    (= (block-relative-bandwidth count-17) 0.3)
    (= (block-relative-bandwidth count-18) 0.3)
    (= (block-relative-bandwidth count-19) 0.3)
    (= (block-relative-bandwidth count-20) 0.3)
    (= (block-relative-bandwidth count-21) 0.3)
    (= (block-relative-bandwidth count-22) 0.3)
    (= (block-relative-bandwidth count-23) 0.3)
    (= (block-relative-bandwidth count-24) 0.3)
    (= (block-relative-bandwidth count-25) 0.3)
    (= (block-relative-bandwidth count-26) 0.3)
    (= (block-relative-bandwidth count-27) 0.3)
    (= (block-relative-bandwidth count-28) 0.3)
    (= (block-relative-bandwidth count-29) 0.3)
    (= (block-relative-bandwidth count-30) 0.3)
)
 (:goal (and
    (in block-0 node-A)
    (in block-1 node-A)
    (in block-2 node-A)
    (in block-3 node-A)
    (in block-4 node-A)
    (in block-5 node-A)
    (in block-6 node-A)
    (in block-7 node-A)
    (in block-8 node-A)
    (in block-9 node-A)
    (in block-10 node-A)
    (in block-11 node-A)
    (in block-12 node-A)
    (in block-13 node-A)
    (in block-14 node-A)
    (in block-15 node-A)
    (in block-16 node-A)
    (in block-17 node-A)
    (in block-18 node-A)
    (in block-19 node-A)
    (in block-20 node-A)
    (in block-21 node-A)
    (in block-22 node-A)
    (in block-23 node-A)
    (in block-24 node-A)
    (in block-25 node-A)
    (in block-26 node-A)
    (in block-27 node-A)
    (in block-28 node-A)
    (in block-29 node-A)
    (in block-0 node-B)
    (in block-1 node-B)
    (in block-2 node-B)
    (in block-3 node-B)
    (in block-4 node-B)
    (in block-5 node-B)
    (in block-6 node-B)
    (in block-7 node-B)
    (in block-8 node-B)
    (in block-9 node-B)
    (in block-10 node-B)
    (in block-11 node-B)
    (in block-12 node-B)
    (in block-13 node-B)
    (in block-14 node-B)
    (in block-15 node-B)
    (in block-16 node-B)
    (in block-17 node-B)
    (in block-18 node-B)
    (in block-19 node-B)
    (in block-20 node-B)
    (in block-21 node-B)
    (in block-22 node-B)
    (in block-23 node-B)
    (in block-24 node-B)
    (in block-25 node-B)
    (in block-26 node-B)
    (in block-27 node-B)
    (in block-28 node-B)
    (in block-29 node-B)
    (in block-0 node-C)
    (in block-1 node-C)
    (in block-2 node-C)
    (in block-3 node-C)
    (in block-4 node-C)
    (in block-5 node-C)
    (in block-6 node-C)
    (in block-7 node-C)
    (in block-8 node-C)
    (in block-9 node-C)
    (in block-10 node-C)
    (in block-11 node-C)
    (in block-12 node-C)
    (in block-13 node-C)
    (in block-14 node-C)
    (in block-15 node-C)
    (in block-16 node-C)
    (in block-17 node-C)
    (in block-18 node-C)
    (in block-19 node-C)
    (in block-20 node-C)
    (in block-21 node-C)
    (in block-22 node-C)
    (in block-23 node-C)
    (in block-24 node-C)
    (in block-25 node-C)
    (in block-26 node-C)
    (in block-27 node-C)
    (in block-28 node-C)
    (in block-29 node-C)
    (in block-0 node-D)
    (in block-1 node-D)
    (in block-2 node-D)
    (in block-3 node-D)
    (in block-4 node-D)
    (in block-5 node-D)
    (in block-6 node-D)
    (in block-7 node-D)
    (in block-8 node-D)
    (in block-9 node-D)
    (in block-10 node-D)
    (in block-11 node-D)
    (in block-12 node-D)
    (in block-13 node-D)
    (in block-14 node-D)
    (in block-15 node-D)
    (in block-16 node-D)
    (in block-17 node-D)
    (in block-18 node-D)
    (in block-19 node-D)
    (in block-20 node-D)
    (in block-21 node-D)
    (in block-22 node-D)
    (in block-23 node-D)
    (in block-24 node-D)
    (in block-25 node-D)
    (in block-26 node-D)
    (in block-27 node-D)
    (in block-28 node-D)
    (in block-29 node-D)
    (in block-0 node-E)
    (in block-1 node-E)
    (in block-2 node-E)
    (in block-3 node-E)
    (in block-4 node-E)
    (in block-5 node-E)
    (in block-6 node-E)
    (in block-7 node-E)
    (in block-8 node-E)
    (in block-9 node-E)
    (in block-10 node-E)
    (in block-11 node-E)
    (in block-12 node-E)
    (in block-13 node-E)
    (in block-14 node-E)
    (in block-15 node-E)
    (in block-16 node-E)
    (in block-17 node-E)
    (in block-18 node-E)
    (in block-19 node-E)
    (in block-20 node-E)
    (in block-21 node-E)
    (in block-22 node-E)
    (in block-23 node-E)
    (in block-24 node-E)
    (in block-25 node-E)
    (in block-26 node-E)
    (in block-27 node-E)
    (in block-28 node-E)
    (in block-29 node-E)
 ))
 (:metric minimize (total-cost))
)
